#+title: Config
This is the document containing all of my configurations
refer to the headers or the table of contents for navigation

*  Table of Contents :TOC_4:
-  [[#scripts-bin-directory][Scripts (bin/ Directory)]]
  -  [[#bash][Bash]]
    -  [[#stow-configs][Stow Configs]]
      -  [[#shebang][Shebang]]
      -  [[#get-script-location-and-project-root][Get Script Location and Project Root]]
      -  [[#create-directories-if-needed][Create directories (if needed)]]
      -  [[#symlink-hardware-configurationnix][Symlink hardware-configuration.nix]]
      -  [[#run-stow][Run Stow]]
  -  [[#clojure-babashka][Clojure (Babashka)]]
    -  [[#directories-edn][Directories (EDN)]]
    -  [[#nix-sys][Nix Sys]]
      -  [[#shebang-and-imports][Shebang and Imports]]
      -  [[#general-variables][General Variables]]
      -  [[#utility-functions][Utility Functions]]
      -  [[#system-config][System Config]]
      -  [[#system-rebuild][System Rebuild]]
      -  [[#system-update][System Update]]
      -  [[#system-help][System Help]]
      -  [[#cli-interface][CLI Interface]]
-  [[#doom-gnu-emacs-doom-directory][Doom GNU Emacs (doom/ Directory)]]
  -  [[#about][About]]
    -  [[#why-emacs][Why Emacs?]]
      -  [[#i-like-lisp][I like lisp]]
      -  [[#developerwriting-environment][Developer/Writing environment]]
      -  [[#customize-everything][Customize everything]]
      -  [[#gui-app][GUI App]]
      -  [[#stability][Stability]]
      -  [[#killer-features][Killer Features]]
  -  [[#init-settings][Init Settings]]
    -  [[#input][Input]]
    -  [[#completion][Completion]]
    -  [[#ui][UI]]
    -  [[#editor][Editor]]
    -  [[#emacs][Emacs]]
    -  [[#term][Term]]
    -  [[#checkers][Checkers]]
    -  [[#tools][Tools]]
    -  [[#os][OS]]
    -  [[#lang][Lang]]
    -  [[#email][Email]]
    -  [[#app][App]]
    -  [[#config][Config]]
  -  [[#config-settings][Config Settings]]
    -  [[#basic-usage][Basic usage]]
      -  [[#basic-variables][Basic variables]]
      -  [[#basic-macros][Basic macros]]
    -  [[#early-emacs-setup][Early Emacs Setup]]
    -  [[#custom-functions][Custom Functions]]
      -  [[#update-script][Update Script]]
      -  [[#rebuild-script][Rebuild Script]]
      -  [[#config-script][Config Script]]
    -  [[#basic-settings][Basic settings]]
      -  [[#keybinds][Keybinds]]
      -  [[#fonts][Fonts]]
      -  [[#theme][Theme]]
      -  [[#line-numbers][Line numbers]]
      -  [[#transparency][Transparency]]
      -  [[#mode-line-settings][Mode Line Settings]]
      -  [[#mode-settings][Mode Settings]]
    -  [[#package-settings][Package settings]]
      -  [[#utilities][Utilities]]
      -  [[#debugger][Debugger]]
      -  [[#elpher][Elpher]]
      -  [[#workspaces][Workspaces]]
      -  [[#org][Org]]
  -  [[#packages-settings][Packages Settings]]
    -  [[#basic-usage-1][Basic usage]]
    -  [[#external-packages][External Packages]]
      -  [[#utils][Utils]]
      -  [[#org-packages][Org Packages]]
      -  [[#ui-1][UI]]
      -  [[#fun][Fun]]
-  [[#home-home-directory][Home (home/ Directory)]]
  -  [[#bashrc-config][Bashrc Config]]
    -  [[#basic-settings-1][Basic Settings]]
    -  [[#history-configuration][History Configuration]]
    -  [[#shell-options][Shell Options]]
    -  [[#prompt][Prompt]]
    -  [[#aliases][Aliases]]
    -  [[#environment-variables][Environment Variables]]
-  [[#hyprland-hypr-directory][Hyprland (hypr/ Directory)]]
  -  [[#hyprland-config][Hyprland Config]]
    -  [[#monitors][Monitors]]
    -  [[#programs][Programs]]
    -  [[#autostart][Autostart]]
    -  [[#environment-variables-1][Environment Variables]]
    -  [[#look-and-feel][Look and Feel]]
      -  [[#general][General]]
      -  [[#decoration][Decoration]]
      -  [[#animations][Animations]]
      -  [[#gaps][Gaps]]
      -  [[#layouts][Layouts]]
      -  [[#misc-variables][Misc Variables]]
    -  [[#input-1][Input]]
    -  [[#keybinds-1][Keybinds]]
      -  [[#main-modifier-key][Main Modifier Key]]
      -  [[#main-keybinds][Main Keybinds]]
      -  [[#movement][Movement]]
      -  [[#workspaces-1][Workspaces]]
      -  [[#move-to-workspaces][Move To Workspaces]]
      -  [[#special-workspaces][Special Workspaces]]
      -  [[#window-resize][Window Resize]]
      -  [[#special-keys][Special Keys]]
      -  [[#windows-and-workspaces][Windows and Workspaces]]
  -  [[#hyprpaper][Hyprpaper]]

*  Scripts (bin/ Directory)
:PROPERTIES:
:VISIBILITY: folded
:END:
**  Bash
***  Stow Configs
:PROPERTIES:
:header-args: :tangle ./bin/stow-configs
:END:
****  Shebang
#+begin_src bash
#!/usr/bin/env nix-shell
#! nix-shell -i bash --pure
#! nix-shell -p bash stow
#+end_src
****  Get Script Location and Project Root
This finds the original script location
#+begin_src bash
PROJECT_DIR=$(dirname "$(dirname "$(readlink -f "$0")")")

echo "Hello World"
#+end_src
****  Create directories (if needed)
#+begin_src bash
mkdir -p ~/.config/doom
mkdir -p ~/.config/waybar
mkdir -p ~/.config/wofi
mkdir -p ~/.config/hypr
mkdir -p ~/.config/kitty
mkdir -p ~/.local/bin
#+end_src

****  Symlink hardware-configuration.nix
#+begin_src bash
if [ ! -L "${PROJECT_DIR}/nixos/hardware-configuration.nix" ]; then
    (cd "${PROJECT_DIR}/nixos" && ln -sr /etc/nixos/hardware-configuration.nix)
fi
#+end_src

****  Run Stow
This will put everything where it needs to go
#+begin_src bash
# Stow packages
(cd "$PROJECT_DIR" && stow doom -t ~/.config/doom)
(cd "$PROJECT_DIR" && stow home -t ~)
(cd "$PROJECT_DIR" && stow bin -t ~/.local/bin)
(cd "$PROJECT_DIR" && stow waybar -t ~/.config/waybar)
(cd "$PROJECT_DIR" && stow hypr -t ~/.config/hypr)
(cd "$PROJECT_DIR" && stow wofi -t ~/.config/wofi)
(cd "$PROJECT_DIR" && stow kitty -t ~/.config/kitty)
#+end_src

**  Clojure (Babashka)
***  Directories (EDN)
:PROPERTIES:
:header-args: :tangle ./bin/directories.edn
:END:
This is an EDN file that's shared between clojure scripts

#+begin_src clojure
[{:name "doom"   :dir "/.config/doom"}
 {:name "home"   :dir "/"}
 {:name "bin"    :dir "/.local/bin"}
 {:name "waybar" :dir "/.config/waybar"}
 {:name "hypr"   :dir "/.config/hypr"}
 {:name "wofi"   :dir "/.config/wofi"}
 {:name "kitty"  :dir "/.config/kitty"}]
#+end_src

***  Nix Sys
:PROPERTIES:
:header-args: :tangle ./bin/nix-sys
:END:
****  Shebang and Imports
#+begin_src clojure
#!/usr/bin/env bb

(require '[babashka.process :refer [shell process check]])
(require '[babashka.fs :as fs])
(require '[clojure.edn :as edn])
#+end_src
****  General Variables
#+begin_src clojure
;; Get the root directory of the true file (not symlink)
(def project-dir
  (->> *file*
       (java.io.File.)
       (.getCanonicalFile)
       (.getParent)
       (java.io.File.)
       (.getParent)))

(def data
  (->> "/bin/directories.edn"
       (str project-dir)
       (slurp)
       (edn/read-string)))

(def dirs
  (map #(str (fs/home) (:dir %)) data))

(def packages (map #(:name %) data))
#+end_src
****  Utility Functions
#+begin_src clojure
(defn configure-directories [dirs]
  (doseq [d dirs]
    (when-not (= d (str (fs/home) "/"))
      (fs/create-dirs d))))

(defn ensure-hardware-symlink [link target]
  (when-not (fs/sym-link? link)
    (fs/create-sym-link
     link
     (fs/relativize (fs/parent link) target))))

(defn configure-stow-links [packages dirs]
  (doseq [[package d] (map vector packages dirs)]
    (-> (process ["stow" package "-t" d])
        check)))
#+end_src

****  System Config
#+begin_src clojure
;; Config system
(defn sys-config
  "Sets the system up correctly"
  []

  ;; Take the hardware-configuration.nix from /etc/ that's auto generated
  ;; When installing nixos
  (ensure-hardware-symlink
   (str project-dir "/nixos/hardware-configuration.nix")
   "/etc/nixos/hardware-configuration.nix")

  ;; Setup directories
  (configure-directories dirs)

  ;; Use stow to install all config file symlinks
  (configure-stow-links packages dirs))
#+end_src

****  System Rebuild
#+begin_src clojure
;; Rebuild system
(defn sys-rebuild []
  (shell
   (str
    "sudo nixos-rebuild switch --flake \""
    project-dir
    "/nixos\" --impure")))
#+end_src

****  System Update
#+begin_src clojure
;; Update then rebuild
(defn sys-update []
  (shell
   (str
    "nix flake update --flake \""
    project-dir
    "/nixos\""))
  (sys-rebuild))
#+end_src

****  System Help
#+begin_src clojure
(defn sys-help []
  (print (apply str
                ["Nix-Sys v0.0.1\n"
                 "Use flags:\n\n"
                 "'-c': Run GNU stow for symlink management along with other commands\n"
                 "'-r': Rebuild NixOS from configs/nixos\n"
                 "'-u': Updates Nixos from configs/nixos\n"
                 "'-h': Shows this page\n"])))
#+end_src

****  CLI Interface
#+begin_src clojure
(when (seq *command-line-args*)
  (doseq [arg *command-line-args*]
    (case arg
      "" (sys-help)
      "-c" (sys-config)
      "-r" (sys-rebuild)
      "-u" (sys-update)
      "-h" (sys-help)
      (sys-help))))
#+end_src

*  Doom GNU Emacs (doom/ Directory)
:PROPERTIES:
:VISIBILITY: folded
:END:
**  About
:PROPERTIES:
:VISIBILITY: folded
:END:

*DISCLAIMER:* The configuration starts after this, so feel free to skip the about section

***  Why Emacs?
I chose Emacs for a couple of reasons.
****  I like lisp
Sometimes it is that simple, I like writing lisp and wanted an editor that is configured with lisp.

****  Developer/Writing environment
I like using tools that enable modal editing and keyboard driven text editing. I also value a tool that keeps everything in one space.
- Development :: Git, Docker, Scripting, Debugging, and READING logs all in Emacs
- Writing :: Org Mode enables to do all my writing in one format then target different formats with tools like pandoc

Nothing is off the table with Emacs, I can write custom functions to do whatever I need and interact with the system through my main environment.

****  Customize everything
Everything can be changed: theme, font, functionality, keybinds, modes, you name it.

****  GUI App
This one is less important, but due to issues with emoji and certain font faces in terminals I had issues with displaying characters in Neovim in the past.

****  Stability
In my experience Emacs has been pretty stable once I got everything working how I liked it. My previous editor (Neovim) had stability issues in the past but from what I've gathered it has gotten better over the years.

****  Killer Features
I used to use Neovim so you might be inclined to ask why do I not switch back? The main reasons are magit and org-mode. Hands down my favorite features of Emacs and keep me here with it.


**  Init Settings
:PROPERTIES:
:header-args: :tangle ./doom/init.el
:VISIBILITY: folded
:END:

This are the settings originally located in *init.el*
To toggle certain settings simply uncomment (remove ;;) a package name.
***  Input
#+begin_src emacs-lisp
(doom! :input
       ;;bidi              ; (tfel ot) thgir etirw uoy gnipleh
       chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row
#+end_src
***  Completion
#+begin_src emacs-lisp
       :completion
       ;;company           ; the ultimate code completion backend
       (corfu +orderless)  ; complete with cap(f), cape and a flying feather!
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       vertico           ; the search engine of the future
#+end_src
***  UI
#+begin_src emacs-lisp
       :ui
       ;;deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       doom-quit         ; DOOM quit-message prompts when you quit Emacs
       ;;(emoji +unicode)  ; 🙂
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       indent-guides     ; highlighted indent columns
       (ligatures +extra)         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;smooth-scroll     ; So smooth you won't believe it's not butter
       ;;tabs              ; a tab bar for Emacs
       treemacs          ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       (vc-gutter +pretty) ; vcs diff in the fringe
       ;;vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       ;;zen               ; distraction-free coding or writing
#+end_src
***  Editor
#+begin_src emacs-lisp
       :editor
       (evil +everywhere) ; come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       (format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       (whitespace +guess +trim)  ; a butler for your whitespace
       word-wrap         ; soft wrapping with language-aware indent
#+end_src
***  Emacs
#+begin_src emacs-lisp
       :emacs
       dired             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       eww               ; the internet is gross
       ibuffer           ; interactive buffer management
       tramp             ; remote files at your arthritic fingertips
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree
#+end_src
***  Term
#+begin_src emacs-lisp
       :term
       eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm             ; the best terminal emulation in Emacs
#+end_src
***  Checkers
#+begin_src emacs-lisp
       :checkers
       syntax              ; tasing you for every semicolon you forget
       (spell +flyspell) ; tasing you for misspelling mispelling
       grammar           ; tasing grammar mistake every you make
#+end_src
***  Tools
#+begin_src emacs-lisp
       :tools
       ;;ansible
       ;;biblio            ; Writes a PhD for you (citation needed)
       ;;collab            ; buffers with friends
       ;;(debugger +lsp)          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       lookup              ; navigate your code and its documentation
       ;;llm               ; when I said you needed friends, I didn't mean...
       (lsp +eglot)      ; M-x vscode
       magit             ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       ;;pdf               ; pdf enhancements
       terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       (tree-sitter
        +everywhere)       ; syntax and parsing, sitting in a tree...
       ;;upload            ; map local to remote projects via ssh/ftp
#+end_src
***  OS
#+begin_src emacs-lisp
       :os
       (:if (featurep :system 'macos) macos)  ; improve compatibility with macOS
       ;;tty               ; improve the terminal Emacs experience
#+end_src
***  Lang
#+begin_src emacs-lisp
       :lang
       ;;ada               ; In strong typing we (blindly) trust
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       ;;(cc +lsp)         ; C > C++ == 1
       clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fortran           ; in FORTRAN, GOD is REAL (unless declared INTEGER)
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       (go +lsp)         ; the hipster dialect
       ;;(graphql +lsp)    ; Give queries a REST
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       json              ; At least it ain't XML
       ;;janet             ; Fun fact: Janet is me!
       ;;(java +lsp)       ; the poster child for carpal tunnel syndrome
       (javascript
        +tree-sitter
        +lsp)        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       latex             ; writing papers in Emacs has never been so fun
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be
       ;;lua               ; one-based indices? one-based indices
       markdown          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org
        +roam)               ; organize your plain life in plain text
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;graphviz          ; diagrams for confusing yourself even more
       ;;purescript        ; javascript, but functional
       (python
        +lsp)            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       ;;rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;(rust +lsp)       ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       sh                ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       web               ; the tubes
       yaml              ; JSON, but readable
       ;;zig               ; C, but simpler
#+end_src
***  Email
#+begin_src emacs-lisp
       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)
#+end_src
***  App
#+begin_src emacs-lisp
       :app
       ;;calendar
       ;;(emms +mpv)         ; music player with mpv backend.
       ;;everywhere        ; *leave* Emacs!? You must be joking
       irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader
#+end_src
***  Config
#+begin_src emacs-lisp
       :config
       ;;literate
       (default +bindings +smartparens))
#+end_src

**  Config Settings
:PROPERTIES:
:header-args: :tangle ./doom/config.el
:VISIBILITY: folded
:END:

This are the settings originally located in *config.el*.
This is where custom Emacs functions and configuration for packages reside.
***  Basic usage
****  Basic variables
+ doom-font                :: the primary font to use
+ doom-variable-pitch-font :: a non-monospace font (where applicable)
+ doom-big-font            :: used for big font
+ doom-symbol-font         :: for symbols
+ doom-serif-font          :: serif font

****  Basic macros
+ after!         :: Used for configuring packages doom might override
+ load!          :: Load external .el files
+ use-package!   :: Configure packages
+ after!         :: For running code after a package has loaded
+ add-load-path! :: For adding directories to the load-path.
+ map!           :: Map new keys
***  Early Emacs Setup
***  Custom Functions
****  Update Script
#+begin_src emacs-lisp
(defun scripts/update
    ()
  "Run update script"
  (interactive)
  (shell-command "nix-sys -u"))
#+end_src
****  Rebuild Script
#+begin_src emacs-lisp
(defun scripts/rebuild
    ()
  "Run rebuild script"
  (interactive)
  (shell-command "nix-sys -r"))
#+end_src
****  Config Script
#+begin_src emacs-lisp
(defun scripts/config
    ()
  "Run config script."
  (interactive)
  (shell-command "stow-configs")
  (message "Done!"))
#+end_src
***  Basic settings
****  Keybinds
*****  Custom Functions
#+begin_src emacs-lisp
(map!
 :prefix "C-c f"
 :desc "Run 'stow-configs' script" "c" #'scripts/config
 :desc "Run 'update-all-packages' script" "u" #'scripts/update)
#+end_src

#+RESULTS:

*****  Dirvish
#+begin_src emacs-lisp
(map!
 "C-c d d" #'dirvish
 "C-c d q" #'dirvish-quit
 "C-c d f" #'dirvish-fd)
#+end_src
*****  Window sizing
#+begin_src emacs-lisp
(global-set-key (kbd "<C-up>"   ) 'shrink-window)
(global-set-key (kbd "<C-down>" ) 'enlarge-window)
(global-set-key (kbd "<C-left>" ) 'shrink-window-horizontally)
(global-set-key (kbd "<C-right>") 'enlarge-window-horizontally)
#+end_src
****  Fonts
*****  Change Font Based on Mode
#+begin_src emacs-lisp
(add-hook 'org-mode-hook
          (lambda () (text-scale-set 1))) ; Make font larger in org mode

(add-hook 'prog-mode-hook
          (lambda () (text-scale-set 0))) ; Reset font for programming modes
#+end_src
*****  Set Font Faces
Will need to download the Iosevka Font for this to work.
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Iosevka Nerd Font Mono" :size 16))
(setq doom-serif-font (font-spec :family "DejaVu Serif" :size 16))

;; Make doom large font even bigger
(setq doom-big-font-increment 6)
#+end_src
****  Theme
#+begin_src emacs-lisp
;; Enable bold and italic for better syntax highlighting
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))

;; Set Theme
(setq doom-theme 'doom-molokai)
#+end_src
***** Borders
#+begin_src emacs-lisp
;; Remove all window borders and dividers
(setq window-divider-default-bottom-width 0
      window-divider-default-right-width 0
      window-divider-default-places nil)
(window-divider-mode -1)

;; Make borders invisible by matching background
(set-face-background 'vertical-border "#000000")
(set-face-foreground 'vertical-border "#000000")

;; Remove fringe (the side margins)
(set-fringe-mode 0)  ; Or use a number like 8 for minimal fringe

;; Optional: make internal borders match your background
(custom-set-faces!
  '(vertical-border :foreground "#000000" :background "#000000")
  '(window-divider :foreground "#000000")
  '(window-divider-first-pixel :foreground "#000000")
  '(window-divider-last-pixel :foreground "#000000"))
#+end_src
****  Line numbers
#+begin_src emacs-lisp
(setq display-line-numbers-type `relative)
#+end_src
****  Transparency
#+begin_verse
Change the numerical values to affect the transparency
(0-100 where 100 is opaque)
#+end_verse
#+begin_src emacs-lisp
(set-frame-parameter (selected-frame) 'alpha '(90 . 90))
(add-to-list 'default-frame-alist '(alpha . (90 . 90)))
#+end_src
****  Mode Line Settings
#+begin_src emacs-lisp
(after! doom-modeline
  ;; Configuration
  (setq doom-modeline-height 40
        doom-modeline-bar-width 6
        doom-modeline-icon t
        doom-modeline-major-mode-icon t
        doom-modeline-major-mode-color-icon t
        doom-modeline-buffer-file-name-style 'truncate-upto-project
        doom-modeline-buffer-encoding t
        doom-modeline-indent-info t
        doom-modeline-lsp t
        doom-modeline-env-version t
        doom-modeline-enable-word-count nil
        doom-modeline-column-zero-based nil
        doom-modeline-minor-modes nil))


(display-time-mode 1)
(display-battery-mode 1)
#+end_src
****  Mode Settings
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.astro\\'" . web-mode))
#+end_src
***  Package settings
****  Utilities
*****  Eshell
******  Prompt
#+begin_src emacs-lisp
(after! eshell
  (require 'magit)

  (setq eshell-prompt-function
        (lambda ()
          (let* ((user (user-login-name))
                 (host (system-name))
                 (pwd  (abbreviate-file-name (eshell/pwd)))
                 (branch (ignore-errors (magit-get-current-branch)))
                 ;; 12-hour time with AM/PM
                 (time (format-time-string "%I:%M %p"))
                 ;; Nerd Font Git branch icon (nf-dev-git_branch)
                 (git-icon "")
                 (git-part (when branch
                             (concat
                              " "
                              (propertize git-icon
                                          'face 'font-lock-constant-face)
                              " "
                              (propertize branch
                                          'face 'font-lock-constant-face)))))
            (concat
             ;; First line
             (propertize (format "[%s@%s]" user host)
                         'face 'font-lock-keyword-face)
             " >>> "
             (propertize pwd 'face 'font-lock-string-face)
             git-part
             "\n"
             ;; Second line
             (propertize time 'face 'font-lock-comment-face)
             " "
             (propertize "λ "
                         'face 'font-lock-function-name-face)))))

  (setq eshell-prompt-regexp "^[^λ]*λ "))
#+end_src
*****  Dired
#+begin_src emacs-lisp
(use-package! nerd-icons-dired
  :hook
  (dired-mode . nerd-icons-dired-mode))
#+end_src
****  Debugger
*****  Main Config
#+begin_src emacs-lisp
(after! dap-mode
  (setq dap-auto-configure-features '(sessions locals controls tooltip))
  (dap-mode 1)
  (dap-ui-mode 1)
#+end_src
*****  Python
Need to install python debugger (look at install.sh)
#+begin_src emacs-lisp
(require 'dap-python)
;; Set python debugger (debugpy)
(setq dap-python-debugger 'debugpy)
#+end_src
*****  Javascript/Typescript
#+begin_src emacs-lisp
(require 'dap-node)
;; Auto-installs debug adapter
(dap-node-setup)
#+end_src
*****  Go
#+begin_src emacs-lisp
(require 'dap-dlv-go))
#+end_src
****  Elpher
#+begin_src emacs-lisp
(map! :after elpher
      :map elpher-mode-map
      "-" #'elpher-back)
#+end_src

****  Workspaces
#+begin_src emacs-lisp
;; Always create projects when switching projects
(setq +workspaces-on-switch-project-behavior t)
#+end_src
****  Org
#+begin_verse
All of my org settings
first my default org directory
#+end_verse
#+begin_src emacs-lisp
(setq org-directory "~/Documents/org")
(after! org
  (setq org-hide-emphasis-markers t))
#+end_src

*****  Org Modern
#+begin_verse
This makes org mode nicer to look at
#+end_verse
#+begin_src emacs-lisp
;; Org modern settings
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  ;; Basic settings
  (setq org-modern-star '("◉" "○" "✸" "✿" "✤" "✜" "◆" "▶")
        org-modern-table-vertical 1
        org-modern-table-horizontal 0.2
        org-modern-list '((43 . "➤") (45 . "–") (42 . "•"))
        org-modern-block-fringe nil
        org-modern-todo-faces
        '(("TODO" :background "red" :foreground "white")
          ("DONE" :background "green" :foreground "white")))

  ;; Source code block settings
  (setq org-src-fontify-natively t      ; Syntax highlight in code blocks
        org-src-tab-acts-natively t      ; Tab works normally in code blocks
        org-src-preserve-indentation t))  ; Preserve indentation
#+end_src
*****  Org Appear
#+begin_src emacs-lisp
(use-package! org-appear
  :after org-modern
  :hook (org-mode . org-appear-mode))
#+END_SRC
*****  Org Download
#+begin_src emacs-lisp
(setq-default org-download-image-dir "~/Pictures/Org")
#+end_src
*****  Org TOC
#+begin_src emacs-lisp
(use-package! toc-org
  :hook (org-mode . toc-org-mode))
#+END_SRC
*****  Olivetti
#+begin_verse
Used to center org documents
#+end_verse
#+begin_src emacs-lisp
(use-package! olivetti
  :hook (org-mode . olivetti-mode)
  :config (setq olivetti-body-width 100))
#+end_src
*****  Misc org settings
#+begin_src emacs-lisp
(after! org
  (setq org-babel-python-command "python3") ; Sets python to "python3"
  (setq org-babel-default-header-args:python '((:results . "output")))) ; Sets results to output
#+end_src

*****  Prettify Symbols Mode
#+begin_src emacs-lisp
(after! org
  ;; Disables these modes that freeze org mode
  (global-prettify-symbols-mode -1)
  (global-prettify-symbols-mode -1))
#+end_src

**  Packages Settings
:PROPERTIES:
:header-args: :tangle ./doom/packages.el
:VISIBILITY: folded
:END:

This are the external dependencies originally in *packages.el*.
Packages outside of what's available for Doom Emacs reside here.

***  Basic usage
1. Declare them here in a `package!' statement,
2. Run 'doom sync' in the shell,
3. Restart Emacs.
NOTE: for more info on packages look at the documentation (SPC h d h) or more specifically
C-h f package\!
***  External Packages
****  Utils
*****  Elpher
#+begin_src emacs-lisp
(package! elpher)
#+end_src
****  Org Packages
*****  Org Modern
#+begin_src emacs-lisp
(package! org-modern)
#+end_src
*****  Org appear
#+begin_src emacs-lisp
(package! org-appear)
#+END_SRC
*****  Org table of contents
#+begin_src emacs-lisp
(package! toc-org)
#+END_SRC
*****  Org Download
#+begin_src emacs-lisp
(package! org-download)
#+end_src
*****  Olivetti
#+begin_src emacs-lisp
(package! olivetti)
#+end_src
****  UI
*****  Nerd Icons (dired)
#+begin_src emacs-lisp
(package! nerd-icons-dired)
#+end_src
****  Fun
*****  Fireplace
#+begin_src emacs-lisp
(package! fireplace)
#+end_src

*  Home (home/ Directory)
:PROPERTIES:
:VISIBILITY: folded
:END:

**  Bashrc Config
:PROPERTIES:
:header-args: :tangle ./home/.bashrc
:VISIBILITY: folded
:END:

This is the bashrc I use for the system
***  Basic Settings
#+begin_src bash
#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
#+end_src
***  History Configuration
#+begin_src bash
HISTSIZE=10000                # Commands to keep in memory
HISTFILESIZE=20000            # Commands to keep in history file
HISTCONTROL=ignoreboth        # Ignore duplicates and commands starting with space
shopt -s histappend           # Append to history file, don't overwrite
#+end_src
***  Shell Options
#+begin_src bash
shopt -s checkwinsize         # Update LINES and COLUMNS after each command
shopt -s globstar 2>/dev/null # Enable ** for recursive glob matching
shopt -s cdspell              # Autocorrect minor spelling errors in cd
#+end_src
***  Prompt
#+begin_src bash
# Function to get current git branch
git_branch() {
    local branch=$(git branch 2>/dev/null | grep '^*' | colrm 1 2)
    if [ -n "$branch" ]; then
        echo "($branch) "
    fi
}

# Prompt

PS1='\[\033[01;32m\][\u@\h]\[\033[00m\] >>> \[\033[01;34m\]\w\[\033[00m\] \[\033[01;33m\]$(git_branch)\[\033[00m\]\n\[\033[01;90m\]\A\[\033[00m\] λ '
#+end_src
***  Aliases
#+begin_src bash
# Listing
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -lAh'
alias l='ls -CF'

# Safety nets
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Shortcuts
alias grep='grep --color=auto'
alias df='df -h'
alias du='du -h'
alias free='free -h'

# Git shortcuts (if you use git)
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'
#+end_src
***  Environment Variables
#+begin_src bash
export EDITOR=emacs
export VISUAL=emacs

# Add your custom PATH modifications below:
export PATH="$HOME/.local/bin:$PATH"

# Doom
export PATH="$HOME/.config/emacs/bin:$PATH"
#+end_src
*  Hyprland (hypr/ Directory)
:PROPERTIES:
:VISIBILITY: folded
:END:

**  Hyprland Config
:PROPERTIES:
:header-args: :tangle ./hypr/hyprland.conf
:VISIBILITY: folded
:END:
This is my hyprland configuration originally modified from an auto generated one.

For more info on configuring hyprland visit the [[https://wiki.hypr.land/Configuring/][Wiki]]
***  Monitors
#+begin_src conf
monitor = DP-2, 1440x900@74.98, -900x0, 1, transform, 1
monitor = HDMI-A-1, 1920x1080@74.97, 0x0, 1
#+end_src
***  Programs
#+begin_src conf
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$editor = emacsclient -cn
#+end_src
***  Autostart
#+begin_src conf
exec-once = hyprpaper & waybar
exec-once = emacs --daemon
#+end_src
***  Environment Variables
#+begin_src conf
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
#+end_src

***  Look and Feel
****  General
#+begin_src conf
general {
    gaps_in = 5
    gaps_out = 10

    border_size = 5

    col.active_border =  rgba(fb2874aa) 45deg
    col.inactive_border = rgba(1c1e1faa)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}
#+end_src
****  Decoration
#+begin_src conf
decoration {
    rounding = 3
    rounding_power = 1

    active_opacity = 0.9
    inactive_opacity = 0.87

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 1
        passes = 1

        vibrancy = 0.1696
    }
}
#+end_src
****  Animations
#+begin_src conf
animations {
    enabled = yes, please :)

    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global,        1,     10,    default
    animation = border,        1,     5.39,  easeOutQuint
    animation = windows,       1,     4.79,  easeOutQuint
    animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
    animation = windowsOut,    1,     1.49,  linear,       popin 87%
    animation = fadeIn,        1,     1.73,  almostLinear
    animation = fadeOut,       1,     1.46,  almostLinear
    animation = fade,          1,     3.03,  quick
    animation = layers,        1,     3.81,  easeOutQuint
    animation = layersIn,      1,     4,     easeOutQuint, fade
    animation = layersOut,     1,     1.5,   linear,       fade
    animation = fadeLayersIn,  1,     1.79,  almostLinear
    animation = fadeLayersOut, 1,     1.39,  almostLinear
    animation = workspaces,    1,     1.94,  almostLinear, fade
    animation = workspacesIn,  1,     1.21,  almostLinear, fade
    animation = workspacesOut, 1,     1.94,  almostLinear, fade
    animation = zoomFactor,    1,     7,     quick
}
#+end_src
****  Gaps
#+begin_src conf
# "Smart gaps" / "No gaps when only"
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding 0, floating:0, onworkspace:f[1]
#+end_src
****  Layouts
*****  Dwindle
#+begin_src conf
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

#+end_src
*****  Master
#+begin_src conf
master {
    new_status = master
}
#+end_src
****  Misc Variables
#+begin_src conf
misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}
#+end_src
***  Input
#+begin_src conf
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
#+end_src
***  Keybinds
****  Main Modifier Key
#+begin_src conf
$mainMod = SUPER # Sets "Windows" key as main modifier
#+end_src
****  Main Keybinds
#+begin_src conf
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, W, exec, $editor
bind = $mainMod, C, killactive,
bind = $mainMod SHIFT, M, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, ., togglesplit, # dwindle
bind = $mainMod, F, fullscreen
#+end_src
****  Movement
#+begin_src conf
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
#+end_src

****  Workspaces
#+begin_src conf
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
#+end_src
****  Move To Workspaces
#+begin_src conf
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
#+end_src
****  Special Workspaces
#+begin_src conf
# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
#+end_src

****  Window Resize
#+begin_src conf
# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
#+end_src

****  Special Keys
#+begin_src conf
# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
#+end_src

****  Windows and Workspaces
#+begin_src conf
# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Bind certain workspaces to certain monitors
workspace = 10, monitor:DP-2, default:true
workspace = 9, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 2, monitor:HDMI-A-1 default: true
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
#+end_src
**  Hyprpaper
:PROPERTIES:
:header-args: :tangle ./hypr/hyprpaper.conf
:VISIBILITY: folded
:END:

#+begin_src conf
preload=~/Pictures/judgement_H_1920x1080.png
preload=~/Pictures/judgement_H_900x1440.png
wallpaper=HDMI-A-1,~/Pictures/judgement_H_1920x1080.png
wallpaper=DP-2,~/Pictures/judgement_H_900x1440.png
#+end_src
