#+title: Config
This is the document containing all of my configurations
refer to the headers or the table of contents for navigation

*  Table of Contents :TOC_4:
-  [[#doom-gnu-emacs-doom-directory][Doom GNU Emacs (doom/ Directory)]]
  -  [[#about][About]]
    -  [[#why-emacs][Why Emacs?]]
      -  [[#i-like-lisp][I like lisp]]
      -  [[#developerwriting-environment][Developer/Writing environment]]
      -  [[#customize-everything][Customize everything]]
      -  [[#gui-app][GUI App]]
      -  [[#stability][Stability]]
      -  [[#killer-features][Killer Features]]
  -  [[#init-settings][Init Settings]]
    -  [[#input][Input]]
    -  [[#completion][Completion]]
    -  [[#ui][UI]]
    -  [[#editor][Editor]]
    -  [[#emacs][Emacs]]
    -  [[#term][Term]]
    -  [[#checkers][Checkers]]
    -  [[#tools][Tools]]
    -  [[#os][OS]]
    -  [[#lang][Lang]]
    -  [[#email][Email]]
    -  [[#app][App]]
    -  [[#config][Config]]
  -  [[#config-settings][Config Settings]]
    -  [[#basic-usage][Basic usage]]
      -  [[#basic-variables][Basic variables]]
      -  [[#basic-macros][Basic macros]]
    -  [[#custom-variables][Custom Variables]]
    -  [[#custom-functions][Custom Functions]]
    -  [[#basic-settings][Basic settings]]
      -  [[#splash-screen][Splash Screen]]
      -  [[#keybinds][Keybinds]]
      -  [[#fonts][Fonts]]
      -  [[#theme][Theme]]
      -  [[#line-numbers][Line numbers]]
      -  [[#transparency][Transparency]]
      -  [[#mode-line-settings][Mode Line Settings]]
      -  [[#mode-settings][Mode Settings]]
      -  [[#review-packages][Review Packages]]
    -  [[#package-settings][Package settings]]
      -  [[#utilities][Utilities]]
      -  [[#emms][EMMS]]
      -  [[#elfeed][Elfeed]]
      -  [[#debugger][Debugger]]
      -  [[#elpher][Elpher]]
      -  [[#workspaces][Workspaces]]
      -  [[#org][Org]]
  -  [[#packages-settings][Packages Settings]]
    -  [[#basic-usage-1][Basic usage]]
    -  [[#external-packages][External Packages]]
      -  [[#utils][Utils]]
      -  [[#org-packages][Org Packages]]
      -  [[#ui-1][UI]]
      -  [[#fun][Fun]]
-  [[#home-home-directory][Home (home/ Directory)]]
  -  [[#bashrc-config][Bashrc Config]]
    -  [[#basic-settings-1][Basic Settings]]
    -  [[#history-configuration][History Configuration]]
    -  [[#fzf][Fzf]]
    -  [[#shell-options][Shell Options]]
    -  [[#prompt][Prompt]]
    -  [[#aliases][Aliases]]
    -  [[#environment-variables][Environment Variables]]
-  [[#hyprland-hypr-directory][Hyprland (hypr/ Directory)]]
  -  [[#monitors][Monitors]]
  -  [[#programs][Programs]]
  -  [[#autostart][Autostart]]
  -  [[#environment-variables-1][Environment Variables]]
  -  [[#look-and-feel][Look and Feel]]
    -  [[#general][General]]
    -  [[#decoration][Decoration]]
    -  [[#animations][Animations]]
    -  [[#gaps][Gaps]]
    -  [[#layouts][Layouts]]
      -  [[#dwindle][Dwindle]]
      -  [[#master][Master]]
    -  [[#xwayland][Xwayland]]
    -  [[#misc-variables][Misc Variables]]
  -  [[#input-1][Input]]
  -  [[#keybinds-1][Keybinds]]
    -  [[#main-modifier-key][Main Modifier Key]]
    -  [[#main-keybinds][Main Keybinds]]
    -  [[#movement][Movement]]
    -  [[#workspaces-1][Workspaces]]
    -  [[#move-to-workspaces][Move To Workspaces]]
    -  [[#special-workspaces][Special Workspaces]]
    -  [[#window-resize][Window Resize]]
    -  [[#special-keys][Special Keys]]
    -  [[#windows-and-workspaces][Windows and Workspaces]]
-  [[#kitty-kitty-directory][Kitty (kitty/ Directory)]]
  -  [[#fonts-1][Fonts]]
  -  [[#cursor][Cursor]]
  -  [[#misc-settings][Misc Settings]]
  -  [[#close-prompt][Close Prompt]]
  -  [[#colors][Colors]]
-  [[#nixos-nixos-directory][NixOS (nixos/ Directory)]]
  -  [[#flake-setttings][Flake Setttings]]
    -  [[#description][Description]]
    -  [[#inputs][Inputs]]
    -  [[#outputs][Outputs]]
  -  [[#home-settings][Home Settings]]
    -  [[#imports][Imports]]
    -  [[#basic-settings-2][Basic Settings]]
    -  [[#packages][Packages]]
      -  [[#browser][Browser]]
  -  [[#configuration-settings][Configuration Settings]]
    -  [[#imports-1][Imports]]
    -  [[#bootloader][Bootloader]]
    -  [[#app-armor][App armor]]
    -  [[#nix-packages-manager][Nix (Packages manager)]]
    -  [[#steam][Steam]]
    -  [[#system][System]]
    -  [[#syncthing][Syncthing]]
    -  [[#hyprland][Hyprland]]
    -  [[#flakes][Flakes]]
    -  [[#desktop][Desktop]]
    -  [[#audio][Audio]]
    -  [[#users][Users]]
    -  [[#docker][Docker]]
    -  [[#flatpak][Flatpak]]
    -  [[#nix-packages][Nix Packages]]
      -  [[#general-dependencies][General Dependencies]]
      -  [[#terminal-kitty][Terminal (kitty)]]
      -  [[#hyprland-1][Hyprland]]
      -  [[#emacs-doom][Emacs (DOOM)]]
      -  [[#fonts-2][Fonts]]
      -  [[#more-developer-tools][More Developer Tools]]
      -  [[#flatpak-1][Flatpak]]
      -  [[#misc][Misc]]
-  [[#waybar-waybar-directory][Waybar (waybar/ directory)]]
  -  [[#basic-settings-3][Basic Settings]]
  -  [[#mpd][MPD]]
  -  [[#idle_inhibitor][Idle_inhibitor]]
  -  [[#tray][Tray]]
  -  [[#clock][Clock]]
  -  [[#cpu][CPU]]
  -  [[#memory][Memory]]
  -  [[#temperature][Temperature]]
  -  [[#backlight][Backlight]]
  -  [[#battery][Battery]]
  -  [[#power-profiles][Power Profiles]]
  -  [[#custom-power][Custom Power]]
  -  [[#network][Network]]
  -  [[#pulseaudio][PulseAudio]]

*  Doom GNU Emacs (doom/ Directory)
:PROPERTIES:
:VISIBILITY: folded
:END:
**  About
:PROPERTIES:
:VISIBILITY: folded
:END:

*DISCLAIMER:* The configuration starts after this, so feel free to skip the about section

***  Why Emacs?
I chose Emacs for a couple of reasons.
****  I like lisp
Sometimes it is that simple, I like writing lisp and wanted an editor that is configured with lisp.

****  Developer/Writing environment
I like using tools that enable modal editing and keyboard driven text editing. I also value a tool that keeps everything in one space.
- Development :: Git, Docker, Scripting, Debugging, and READING logs all in Emacs
- Writing :: Org Mode enables to do all my writing in one format then target different formats with tools like pandoc

Nothing is off the table with Emacs, I can write custom functions to do whatever I need and interact with the system through my main environment.

****  Customize everything
Everything can be changed: theme, font, functionality, keybinds, modes, you name it.

****  GUI App
This one is less important, but due to issues with emoji and certain font faces in terminals I had issues with displaying characters in Neovim in the past.

****  Stability
In my experience Emacs has been pretty stable once I got everything working how I liked it. My previous editor (Neovim) had stability issues in the past but from what I've gathered it has gotten better over the years.

****  Killer Features
I used to use Neovim so you might be inclined to ask why do I not switch back? The main reasons are magit and org-mode. Hands down my favorite features of Emacs and keep me here with it.


**  Init Settings
:PROPERTIES:
:header-args: :tangle ./doom/init.el
:VISIBILITY: folded
:END:

This are the settings originally located in *init.el*
To toggle certain settings simply uncomment (remove ;;) a package name.
***  Input
#+begin_src emacs-lisp
(doom! :input
       ;;bidi              ; (tfel ot) thgir etirw uoy gnipleh
       chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row
#+end_src
***  Completion
#+begin_src emacs-lisp
       :completion
       ;;company           ; the ultimate code completion backend
       (corfu +orderless)  ; complete with cap(f), cape and a flying feather!
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       vertico           ; the search engine of the future
#+end_src
***  UI
#+begin_src emacs-lisp
       :ui
       ;;deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       doom-quit         ; DOOM quit-message prompts when you quit Emacs
       ;;(emoji +unicode)  ; 🙂
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       indent-guides     ; highlighted indent columns
       ;;(ligatures +extra)         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       smooth-scroll     ; So smooth you won't believe it's not butter
       ;;tabs              ; a tab bar for Emacs
       ;;treemacs          ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       (vc-gutter +pretty) ; vcs diff in the fringe
       ;;vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       ;;zen               ; distraction-free coding or writing
#+end_src
***  Editor
#+begin_src emacs-lisp
       :editor
       (evil +everywhere) ; come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       (format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       (whitespace +guess +trim)  ; a butler for your whitespace
       word-wrap         ; soft wrapping with language-aware indent
#+end_src
***  Emacs
#+begin_src emacs-lisp
       :emacs
       dired             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       eww               ; the internet is gross
       ibuffer           ; interactive buffer management
       tramp             ; remote files at your arthritic fingertips
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree
#+end_src
***  Term
#+begin_src emacs-lisp
       :term
       eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm             ; the best terminal emulation in Emacs
#+end_src
***  Checkers
#+begin_src emacs-lisp
       :checkers
       syntax              ; tasing you for every semicolon you forget
       (spell +flyspell) ; tasing you for misspelling mispelling
       grammar           ; tasing grammar mistake every you make
#+end_src
***  Tools
#+begin_src emacs-lisp
       :tools
       ;;ansible
       ;;biblio            ; Writes a PhD for you (citation needed)
       ;;collab            ; buffers with friends
       (debugger +eglot)          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       lookup              ; navigate your code and its documentation
       ;;llm               ; when I said you needed friends, I didn't mean...
       (lsp +eglot)      ; M-x vscode
       magit             ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       pdf               ; pdf enhancements
       terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       (tree-sitter
        +everywhere)       ; syntax and parsing, sitting in a tree...
       ;;upload            ; map local to remote projects via ssh/ftp
#+end_src
***  OS
#+begin_src emacs-lisp
       :os
       (:if (featurep :system 'macos) macos)  ; improve compatibility with macOS
       ;;tty               ; improve the terminal Emacs experience
#+end_src
***  Lang
#+begin_src emacs-lisp
       :lang
       ;;ada               ; In strong typing we (blindly) trust
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       ;;(cc +lsp)         ; C > C++ == 1
       clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fortran           ; in FORTRAN, GOD is REAL (unless declared INTEGER)
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       (go +lsp)         ; the hipster dialect
       ;;(graphql +lsp)    ; Give queries a REST
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       json              ; At least it ain't XML
       ;;janet             ; Fun fact: Janet is me!
       ;;(java +lsp)       ; the poster child for carpal tunnel syndrome
       (javascript
        +tree-sitter
        +lsp)        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       latex             ; writing papers in Emacs has never been so fun
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be
       ;;lua               ; one-based indices? one-based indices
       markdown          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org
        +roam)               ; organize your plain life in plain text
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;graphviz          ; diagrams for confusing yourself even more
       ;;purescript        ; javascript, but functional
       (python
        +lsp)            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       ;;rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;(rust +lsp)       ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       sh                ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       web               ; the tubes
       yaml              ; JSON, but readable
       ;;zig               ; C, but simpler
#+end_src
***  Email
#+begin_src emacs-lisp
       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)
#+end_src
***  App
#+begin_src emacs-lisp
       :app
       calendar
       (emms +mpv)         ; music player with mpv backend.
       ;;everywhere        ; *leave* Emacs!? You must be joking
       irc               ; how neckbeards socialize
       (rss +org)        ; emacs as an RSS reader
#+end_src
***  Config
#+begin_src emacs-lisp
       :config
       ;;literate
       (default +bindings +smartparens))
#+end_src

**  Config Settings
:PROPERTIES:
:header-args: :tangle ./doom/config.el
:VISIBILITY: folded
:END:

This are the settings originally located in *config.el*.
This is where custom Emacs functions and configuration for packages reside.
***  Basic usage
****  Basic variables
+ doom-font                :: the primary font to use
+ doom-variable-pitch-font :: a non-monospace font (where applicable)
+ doom-big-font            :: used for big font
+ doom-symbol-font         :: for symbols
+ doom-serif-font          :: serif font

****  Basic macros
+ after!         :: Used for configuring packages doom might override
+ load!          :: Load external .el files
+ use-package!   :: Configure packages
+ after!         :: For running code after a package has loaded
+ add-load-path! :: For adding directories to the load-path.
+ map!           :: Map new keys
***  Custom Variables
#+begin_src elisp
(defvar project-root
  (file-name-directory
   (directory-file-name
    (file-name-directory
     (file-truename (or load-file-name buffer-file-name))))))
#+end_src
***  Custom Functions
#+begin_src elisp
(defun hypr/launch-vterm
    ()
  "Open a new frame with a vterm buffer."
  (+vterm/here 0)
  (switch-to-buffer "*vterm*"))

(defun hypr/launch-eshell
    ()
  "Open a new eshell frame if one doesn't exist. Otherwise open new eshell buffer."
  (if (get-buffer "*doom:eshell*")
      (switch-to-buffer "*doom:eshell*")
    (progn
      (+eshell/here 0)
      (switch-to-buffer "*doom:eshell*")
      (eshell/clear))))

(defun hypr/launch-elfeed
    ()
  (elfeed)
  (elfeed-update)
  (switch-to-buffer "*elfeed-search*"))

(defun hypr/launch-scratch
    ()
  (scratch-buffer)
  (switch-to-buffer "*scratch*"))
#+end_src
***  Basic settings
****  Splash Screen
#+begin_src elisp
(setq fancy-splash-image "~/Pictures/wallpapers/Pics/Emacs-logo.svg.png")
#+end_src
****  Keybinds
*****  Custom Functions
#+begin_src emacs-lisp
(map!
 :prefix "C-c s"
 :desc "Run 'stow-configs' script" "c" #'scripts/config
 :desc "Run 'update-all-packages' script" "u" #'scripts/update)
#+end_src

*****  Open File
#+begin_src emacs-lisp
(map!
 :prefix "C-c o f"
 :desc "Open notes.org" "n" #'(lambda ()
                                (interactive)
                                (find-file
                                 (concat org-directory "/notes.org")))
 :desc "Open config.org" "c" #'(lambda ()
                                 (interactive)
                                 (find-file
                                  (concat project-root "config.org"))))
#+end_src

*****  EMMS
#+begin_src emacs-lisp
(map!
 :prefix "C-c m"
 :desc "Open EMMS" "e" #'emms
 :desc "Pause EMMS" "t" #'emms-pause
 :desc "Refresh EMMS" "R" #'(lambda ()
                              (interactive)
                              (emms-add-directory "~/Music")
                              (emms))
 :desc "Seek forward" "l" #'emms-seek-forward
 :desc "Seek backwards" "h" #'emms-seek-backward
 :desc "Next Track" "j" #'emms-next
 :desc "Previous track" "k" #'emms-previous)
#+end_src
*****  Elfeed
#+begin_src emacs-lisp
(map!
 :prefix "C-c n"
 :desc "Open elfeed" "f" #'elfeed
 :desc "Unjam elfeed" "u" #'elfeed-unjam
 :desc "Update elfeed" "U" #'elfeed-update)
#+end_src

*****  Window sizing
#+begin_src emacs-lisp
(global-set-key (kbd "<C-up>"   ) 'shrink-window)
(global-set-key (kbd "<C-down>" ) 'enlarge-window)
(global-set-key (kbd "<C-left>" ) 'shrink-window-horizontally)
(global-set-key (kbd "<C-right>") 'enlarge-window-horizontally)
#+end_src
****  Fonts
*****  Change Font Based on Mode
#+begin_src emacs-lisp
(add-hook 'org-mode-hook
          (lambda () (text-scale-set 1))) ; Make font larger in org mode

(add-hook 'prog-mode-hook
          (lambda () (text-scale-set 0))) ; Reset font for programming modes
#+end_src
*****  Set Font Faces
Will need to download the Iosevka Font for this to work.
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Iosevka Nerd Font Mono" :size 16))
(setq doom-serif-font (font-spec :family "DejaVu Serif" :size 16))

;; Make doom large font even bigger
(setq doom-big-font-increment 6)
#+end_src
****  Theme
#+begin_src emacs-lisp
;; Enable bold and italic for better syntax highlighting
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t)
  (setq doom-monokai-classic-brighter-comments t))

;; Set Theme
(setq doom-theme 'doom-monokai-classic)
#+end_src
***** Borders
#+begin_src emacs-lisp
;; Remove all window borders and dividers
(setq window-divider-default-bottom-width 0
      window-divider-default-right-width 0
      window-divider-default-places nil)
(window-divider-mode -1)

;; Make borders invisible by matching background
(set-face-background 'vertical-border "#000000")
(set-face-foreground 'vertical-border "#000000")

;; Remove fringe (the side margins)
(set-fringe-mode 0)  ; Or use a number like 8 for minimal fringe

;; Optional: make internal borders match your background
(custom-set-faces!
  '(vertical-border :foreground "#000000" :background "#000000")
  '(window-divider :foreground "#000000")
  '(window-divider-first-pixel :foreground "#000000")
  '(window-divider-last-pixel :foreground "#000000"))
#+end_src
****  Line numbers
#+begin_src emacs-lisp
(setq display-line-numbers-type `relative)
#+end_src
****  Transparency
#+begin_verse
Change the numerical values to affect the transparency
(0-100 where 100 is opaque)
#+end_verse
#+begin_src emacs-lisp
(set-frame-parameter (selected-frame) 'alpha '(90 . 90))
(add-to-list 'default-frame-alist '(alpha . (90 . 90)))
#+end_src
****  Mode Line Settings
#+begin_src emacs-lisp
(after! doom-modeline
  ;; Configuration
  (setq doom-modeline-height 40
        doom-modeline-bar-width 6
        doom-modeline-icon t
        doom-modeline-major-mode-icon t
        doom-modeline-major-mode-color-icon t
        doom-modeline-buffer-file-name-style 'truncate-upto-project
        doom-modeline-buffer-encoding t
        doom-modeline-indent-info t
        doom-modeline-lsp t
        doom-modeline-env-version t
        doom-modeline-enable-word-count nil
        doom-modeline-column-zero-based nil
        doom-modeline-minor-modes nil))


(display-time-mode 1)
#+end_src
****  Mode Settings
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.astro\\'" . web-mode))
#+end_src
****  Review Packages
#+begin_src emacs-lisp
(setq package-review-policy t
      package-review-diff-command '("git" "diff" "--no-index" "--color=never" "--diff-filter=d"))
#+end_src
***  Package settings
****  Utilities
*****  Eshell
******  Prompt
#+begin_src emacs-lisp
(after! eshell
  (require 'magit)

  (setq eshell-prompt-function
        (lambda ()
          (let* ((user (user-login-name))
                 (emacs (format "GNU EMACS-%s" emacs-version))
                 (pwd  (abbreviate-file-name (eshell/pwd)))
                 (branch (ignore-errors (magit-get-current-branch)))
                 ;; 12-hour time with AM/PM
                 (time (format-time-string "%I:%M %p"))
                 ;; Nerd Font Git branch icon (nf-dev-git_branch)
                 (git-icon "")
                 (git-part (when branch
                             (concat
                              " "
                              (propertize git-icon
                                          'face 'font-lock-constant-face)
                              " "
                              (propertize branch
                                          'face 'font-lock-constant-face)))))
            (concat
             ;; First line
             (propertize (format "[%s@EMACS]" user)
                         'face 'font-lock-keyword-face)
             " |> "
             (propertize pwd 'face 'font-lock-string-face)
             git-part
             "\n"
             ;; Second line
             (propertize emacs 'face 'font-lock-comment-face)
             "\n"
             (propertize time 'face 'font-lock-comment-face)
             " "
             (propertize "λ "
                         'face 'font-lock-function-name-face)))))

  (setq eshell-prompt-regexp "^[^λ]*λ "))
#+end_src
*****  Dired
#+begin_src emacs-lisp
(use-package! nerd-icons-dired
  :hook
  (dired-mode . nerd-icons-dired-mode))
#+end_src
****  EMMS
#+begin_src emacs-lisp
(setq emms-source-file-default-directory "~/Music/")
#+end_src
****  Elfeed
#+begin_src emacs-lisp
(after! elfeed
  (setq rmh-elfeed-org-files (list "~/Documents/org/elfeed.org")))
#+end_src
****  Debugger
*****  Main Config
#+begin_src emacs-lisp
(after! dap-mode
  (setq dap-auto-configure-features '(sessions locals controls tooltip))
  (dap-mode 1)
  (dap-ui-mode 1)
#+end_src
*****  Python
Need to install python debugger (look at install.sh)
#+begin_src emacs-lisp
(require 'dap-python)
;; Set python debugger (debugpy)
(setq dap-python-debugger 'debugpy)
#+end_src
*****  Javascript/Typescript
#+begin_src emacs-lisp
(require 'dap-node)
;; Auto-installs debug adapter
(dap-node-setup)
#+end_src
*****  Go
#+begin_src emacs-lisp
(require 'dap-dlv-go))
#+end_src
****  Elpher
#+begin_src emacs-lisp
(map! :after elpher
      :map elpher-mode-map
      "-" #'elpher-back)
#+end_src

****  Workspaces
#+begin_src emacs-lisp
;; Always create projects when switching projects
(setq +workspaces-on-switch-project-behavior t)
#+end_src
****  Org
#+begin_verse
All of my org settings
first my default org directory
#+end_verse
#+begin_src emacs-lisp
(after! org
  (setq org-agenda-files '("~/Documents/org/agenda/agenda.org"))
  (setq org-directory "~/Documents/org")
  (setq org-hide-emphasis-markers t))
#+end_src

*****  Org Modern
#+begin_verse
This makes org mode nicer to look at
#+end_verse
#+begin_src emacs-lisp
;; Org modern settings
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  ;; Basic settings
  (setq org-modern-star '("◉" "○" "✸" "✿" "✤" "✜" "◆" "▶")
        org-modern-table-vertical 1
        org-modern-table-horizontal 0.2
        org-modern-list '((43 . "➤") (45 . "–") (42 . "•"))
        org-modern-block-fringe nil
        org-modern-todo-faces
        '(("TODO" :background: "gray" :foreground "yellow")
          ("DONE" :background "gray" :foreground "green")))

  ;; Source code block settings
  (setq org-src-fontify-natively t      ; Syntax highlight in code blocks
        org-src-tab-acts-natively t      ; Tab works normally in code blocks
        org-src-preserve-indentation t))  ; Preserve indentation
#+end_src
*****  Org Appear
#+begin_src emacs-lisp
(use-package! org-appear
  :after org-modern
  :hook (org-mode . org-appear-mode))
#+END_SRC
*****  Org Download
#+begin_src emacs-lisp
(setq-default org-download-image-dir "~/Pictures/Org")
#+end_src
*****  Org TOC
#+begin_src emacs-lisp
(use-package! toc-org
  :hook (org-mode . toc-org-mode))
#+END_SRC
*****  Olivetti
#+begin_verse
Used to center org documents
#+end_verse
#+begin_src emacs-lisp
(use-package! olivetti
  :hook (org-mode . olivetti-mode)
  :init (setq olivetti-body-width 100))
#+end_src
*****  Misc org settings
#+begin_src emacs-lisp
(after! org
  (setq org-babel-python-command "python3") ; Sets python to "python3"
  (setq org-babel-default-header-args:python '((:results . "output")))) ; Sets results to output
#+end_src

*****  Prettify Symbols Mode
#+begin_src emacs-lisp
(after! org
  ;; Disables these modes that freeze org mode
  (global-prettify-symbols-mode -1)
  (global-prettify-symbols-mode -1))
#+end_src

**  Packages Settings
:PROPERTIES:
:header-args: :tangle ./doom/packages.el
:VISIBILITY: folded
:END:

This are the external dependencies originally in *packages.el*.
Packages outside of what's available for Doom Emacs reside here.

***  Basic usage
1. Declare them here in a `package!' statement,
2. Run 'doom sync' in the shell,
3. Restart Emacs.
NOTE: for more info on packages look at the documentation (SPC h d h) or more specifically
C-h f package\!
***  External Packages
****  Utils
*****  Elpher
#+begin_src emacs-lisp
(package! elpher)
#+end_src
****  Org Packages
*****  Org Modern
#+begin_src emacs-lisp
(package! org-modern)
#+end_src
*****  Org appear
#+begin_src emacs-lisp
(package! org-appear)
#+END_SRC
*****  Org table of contents
#+begin_src emacs-lisp
(package! toc-org)
#+END_SRC
*****  Org Download
#+begin_src emacs-lisp
(package! org-download)
#+end_src
*****  Olivetti
#+begin_src emacs-lisp
(package! olivetti)
#+end_src
****  UI
*****  Nerd Icons (dired)
#+begin_src emacs-lisp
(package! nerd-icons-dired)
#+end_src
****  Fun
*****  Fireplace
#+begin_src emacs-lisp
(package! fireplace)
#+end_src

*  Home (home/ Directory)
:PROPERTIES:
:VISIBILITY: folded
:END:

**  Bashrc Config
:PROPERTIES:
:header-args: :tangle ./home/.bashrc
:VISIBILITY: folded
:END:

This is the bashrc I use for the system
***  Basic Settings
#+begin_src bash
#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
#+end_src
***  History Configuration
#+begin_src bash
HISTSIZE=10000                # Commands to keep in memory
HISTFILESIZE=20000            # Commands to keep in history file
HISTCONTROL=ignoreboth        # Ignore duplicates and commands starting with space
shopt -s histappend           # Append to history file, don't overwrite
#+end_src
***  Fzf
#+begin_src bash
# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"
#+end_src
***  Shell Options
#+begin_src bash
shopt -s checkwinsize         # Update LINES and COLUMNS after each command
shopt -s globstar 2>/dev/null # Enable ** for recursive glob matching
shopt -s cdspell              # Autocorrect minor spelling errors in cd
#+end_src
***  Prompt
#+begin_src bash
# Function to get current git branch
git_branch() {
    local branch=$(git branch 2>/dev/null | grep '^*' | colrm 1 2)
    if [ -n "$branch" ]; then
        echo "($branch) "
    fi
}

# Prompt

PS1='\[\033[01;32m\][\u@\h]\[\033[00m\] >>> \[\033[01;34m\]\w\[\033[00m\] \[\033[01;33m\]$(git_branch)\[\033[00m\]\n\[\033[01;90m\]\A\[\033[00m\] $ '
#+end_src
***  Aliases
#+begin_src bash
# Listing
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -lAh'
alias l='ls -CF'

# Safety nets
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Shortcuts
alias grep='grep --color=auto'
alias df='df -h'
alias du='du -h'
alias free='free -h'

# Git shortcuts (if you use git)
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'

# Fzf
alias efzf='emacsclient -tty $(fzf -m --preview="cat {}")'
alias nfzf='nvim $(fzf -m --preview="cat {}")'
#+end_src

***  Environment Variables
#+begin_src bash
export EDITOR='emacsclient -tty'
export VISUAL='emacsclient -tty'

# Add your custom PATH modifications below:
export PATH="$HOME/.local/bin:$PATH"

# Doom
export PATH="$HOME/.config/emacs/bin:$PATH"
#+end_src
*  Hyprland (hypr/ Directory)
:PROPERTIES:
:header-args: :tangle ./hypr/hyprland.conf
:VISIBILITY: folded
:END:

This is my hyprland configuration originally modified from an auto generated one.

For more info on configuring hyprland visit the [[https://wiki.hypr.land/Configuring/][Wiki]]
**  Monitors
#+begin_src conf
monitor = DP-2, 1440x900@74.98, -900x0, 1, transform, 1
monitor = HDMI-A-1, 1920x1080@74.97, 0x0, 1
#+end_src
**  Programs
#+begin_src conf
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$editor = emacsclient -cn
$vterm = emacsclient -c -e '(hypr/launch-vterm)'
$eshell = emacsclient -c -e '(hypr/launch-eshell)'
$elfeed = emacsclient -c -e '(hypr/launch-elfeed)'
$scratch = emacsclient -c -e '(hypr/launch-scratch)'
$dired = emacsclient -c -e '(dired ".")'
#+end_src
**  Autostart
#+begin_src conf
exec-once = waybar
exec-once = waypaper --restore
exec-once = emacs --daemon
#+end_src
**  Environment Variables
#+begin_src conf
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
#+end_src

**  Look and Feel
***  General
#+begin_src conf
general {
    gaps_in = 5
    gaps_out = 10

    border_size = 5

    col.active_border =  rgba(fb2874aa) 45deg
    col.inactive_border = rgba(1c1e1faa)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}
#+end_src
***  Decoration
#+begin_src conf
decoration {
    rounding = 3
    rounding_power = 1

    active_opacity = 0.9
    inactive_opacity = 0.87

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 1
        passes = 1

        vibrancy = 0.1696
    }
}
#+end_src
***  Animations
#+begin_src conf
animations {
    enabled = yes, please :)

    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global,        1,     10,    default
    animation = border,        1,     5.39,  easeOutQuint
    animation = windows,       1,     4.79,  easeOutQuint
    animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
    animation = windowsOut,    1,     1.49,  linear,       popin 87%
    animation = fadeIn,        1,     1.73,  almostLinear
    animation = fadeOut,       1,     1.46,  almostLinear
    animation = fade,          1,     3.03,  quick
    animation = layers,        1,     3.81,  easeOutQuint
    animation = layersIn,      1,     4,     easeOutQuint, fade
    animation = layersOut,     1,     1.5,   linear,       fade
    animation = fadeLayersIn,  1,     1.79,  almostLinear
    animation = fadeLayersOut, 1,     1.39,  almostLinear
    animation = workspaces,    1,     1.94,  almostLinear, fade
    animation = workspacesIn,  1,     1.21,  almostLinear, fade
    animation = workspacesOut, 1,     1.94,  almostLinear, fade
    animation = zoomFactor,    1,     7,     quick
}
#+end_src
***  Gaps
#+begin_src conf
# "Smart gaps" / "No gaps when only"
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding 0, floating:0, onworkspace:f[1]
#+end_src
***  Layouts
****  Dwindle
#+begin_src conf
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

#+end_src
****  Master
#+begin_src conf
master {
    new_status = master
}
#+end_src
***  Xwayland
#+begin_src conf
xwayland {
    force_zero_scaling = true
}
#+end_src
***  Misc Variables
#+begin_src conf
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}
#+end_src
**  Input
#+begin_src conf
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
#+end_src
**  Keybinds
***  Main Modifier Key
#+begin_src conf
$mainMod = SUPER # Sets "Windows" key as main modifier
#+end_src
***  Main Keybinds
#+begin_src conf
bind = $mainMod, Q, exec, $vterm
bind = $mainMod SHIFT, Q, exec, $terminal
bind = $mainMod, W, exec, $eshell
bind = $mainMod, E, exec, $editor
bind = $mainMod SHIFT, E, exec, $scratch
bind = $mainMod, R, exec, $menu
bind = $mainMod, N, exec, $elfeed
bind = $mainMod, D, exec, $dired

bind = $mainMod, C, killactive,
bind = $mainMod SHIFT, M, exit,
bind = $mainMod, V, togglefloating,
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, ., togglesplit, # dwindle
bind = $mainMod, F, fullscreen
#+end_src
***  Movement
#+begin_src conf
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
#+end_src

***  Workspaces
#+begin_src conf
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10
#+end_src
***  Move To Workspaces
#+begin_src conf
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
#+end_src
***  Special Workspaces
#+begin_src conf
# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
#+end_src

***  Window Resize
#+begin_src conf
# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
#+end_src

***  Special Keys
#+begin_src conf
# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
#+end_src

***  Windows and Workspaces
#+begin_src conf
# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Bind certain workspaces to certain monitors
workspace = 10, monitor:DP-2, default:true
workspace = 9, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 2, monitor:HDMI-A-1 default: true
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
#+end_src
*  Kitty (kitty/ Directory)
:PROPERTIES:
:header-args: :tangle ./kitty/kitty.conf
:VISIBILITY: folded
:END:
**  Fonts
#+begin_src conf
font_family      Iosevka Nerd Font Mono Light
bold_font        Iosevka Nerd Font Mono
italic_font      Iosevka Nerd Font Mono Light Italic
bold_italic_font Iosevka Nerd Font Mono Italic
font_size        13.0
#+end_src

**  Cursor
#+begin_src conf
cursor                #f92672
cursor_text_color     #1b1d1e
cursor_shape          block
cursor_blink_interval 0
#+end_src
**  Misc Settings
#+begin_src conf
scrollback_lines 10000

window_padding_width 8
#+end_src
**  Close Prompt
#+begin_src conf
confirm_os_window_close 0
#+end_src

**  Colors
Mine are set to resemble molokai
#+begin_src conf
# Background / Foreground
background            #1b1d1e
foreground            #f8f8f2

# Selection
selection_background  #f92672
selection_foreground  #1b1d1e

# Black
color0  #1b1d1e
color8  #75715e

# Red
color1  #f92672
color9  #f92672

# Green
color2  #a6e22e
color10 #a6e22e

# Yellow
color3  #e6db74
color11 #e6db74

# Blue
color4  #66d9e8
color12 #66d9e8

# Magenta
color5  #ae81ff
color13 #ae81ff

# Cyan
color6  #66d9e8
color14 #66d9e8

# White
color7  #f8f8f2
color15 #f8f8f2
#+end_src

*  NixOS (nixos/ Directory)
:PROPERTIES:
:VISIBILITY: folded
:END:
**  Flake Setttings
:PROPERTIES:
:header-args: :tangle ./nixos/flake.nix
:VISIBILITY: folded
:END:
***  Description
#+begin_src nix
{
  description = "My system flake";
#+end_src

***  Inputs
#+begin_src nix
inputs = {
  # NixOS official package source, using the nixos-25.11 branch here
  nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
  # Home manager
  home-manager = {
    url = "github:nix-community/home-manager/release-25.11";
    inputs.nixpkgs.follows = "nixpkgs";
  };
};
#+end_src

***  Outputs
#+begin_src nix
outputs = { self, nixpkgs, home-manager, ... }@inputs: {
  nixosConfigurations.nixos = nixpkgs.lib.nixosSystem {
    modules = [
      # Import the previous configuration.nix we used,
      # so the old configuration file still takes effect
      ./configuration.nix

      # Import home manager
      home-manager.nixosModules.home-manager
      {
        home-manager.useGlobalPkgs = true;
        home-manager.useUserPackages = true;
        home-manager.users.primary = import ./home.nix;
      }
    ];
  };
};
}
#+end_src

**  Home Settings
:PROPERTIES:
:header-args: :tangle ./nixos/home.nix
:VISIBILITY: folded
:END:

***  Imports
#+begin_src nix
{ config, lib, pkgs, ... }:
#+end_src
***  Basic Settings
#+begin_src nix
{
  home.username = "primary";
  home.homeDirectory = "/home/primary";
  home.stateVersion = "25.11";
#+end_src


***  Packages
****  Browser
#+begin_src nix
# Start of the home packages array
home.packages = with pkgs; [
  brave
];
}
#+end_src

**  Configuration Settings
:PROPERTIES:
:header-args: :tangle ./nixos/configuration.nix
:VISIBILITY: folded
:END:
***  Imports
#+begin_src nix
{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

#+end_src

***  Bootloader
#+begin_src nix
  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
#+end_src

***  App armor
#+begin_src nix
  # App armor
  security.apparmor.enable = true;
#+end_src
***  Nix (Packages manager)
#+begin_src nix
nix.package = pkgs.nixVersions.latest;
#+end_src
***  Steam
#+begin_src nix
  # Steam
  programs.steam.enable = true;
#+end_src

***  System
#+begin_src nix
# Use latest kernel.
boot.kernelPackages = pkgs.linuxPackages_latest;

networking.hostName = "nixos"; # Define your hostname.
# networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

# Configure network proxy if necessary
# networking.proxy.default = "http://user:password@proxy:port/";
# networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

# Enable networking
networking.networkmanager.enable = true;

# Set your time zone.
time.timeZone = "America/Chicago";

# Select internationalisation properties.

i18n = {
  defaultLocale = "en_US.UTF-8";

  extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  supportedLocales = [
    "en_US.UTF-8/UTF-8"
    "zh_CN.UTF-8/UTF-8"
  ];

  inputMethod = {
    # Available since NixOS 24.11
    enable = true;
    type = "fcitx5";
    fcitx5 = {
      waylandFrontend = true;
      ignoreUserConfig = true;    # Use settings below, ignore user config
      addons = with pkgs; [
        fcitx5-chewing    # Chewing (Traditional Chinese)
        qt6Packages.fcitx5-chinese-addons
        fcitx5-mozc       # Japanese input method
      ];
      settings = {
        inputMethod = {
          "Groups/0" = {
            Name = "Default";
            "Default Layout" = "us";
            DefaultIM = "keyboard-us";
          };
          "Groups/0/Items/0".Name = "keyboard-us";
          "Groups/0/Items/1".Name = "chewing";
          "Groups/0/Items/2".Name = "mozc";
        };
      };
    };
  };
};

# Backup browser
programs.firefox.enable = true;

nixpkgs.config.allowUnfree = true;

networking.firewall.enable = true;

# This value determines the NixOS release from which the default
# settings for stateful data, like file locations and database versions
# on your system were taken. It‘s perfectly fine and recommended to leave
# this value at the release version of the first install of this system.
# Before changing this value read the documentation for this option
# (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
system.stateVersion = "25.05"; # Did you read the comment?
#+end_src
***  Syncthing
#+begin_src nix
# Example for /etc/nixos/configuration.nix
services.syncthing = {
  enable = true;
  openDefaultPorts = true; # Open ports in the firewall for Syncthing. (NOTE: this will not open syncthing gui port)
  user = "primary";
  dataDir = "/home/primary";
};
#+end_src
***  Hyprland
#+begin_src nix
programs.hyprland.enable = true;

# Optional, hint Electron apps to use Wayland:
environment.sessionVariables.NIXOS_OZONE_WL = "1";
#+end_src
***  Flakes
#+begin_src nix
  # Enable flakes
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
#+end_src

***  Desktop
#+begin_src nix
  # Enable the X11 windowing system.
  # You can disable this if you're only using the Wayland session.
  services.xserver.enable = true;

  # Enable the KDE Plasma Desktop Environment.
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true;

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Set editor to neovim for quick edits
  environment.variables.EDITOR = "nvim";
#+end_src

***  Audio
#+begin_src nix
  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    # If you want to use JACK applications, uncomment this
    #jack.enable = true;

    # use the example session manager (no others are packaged yet so this is enabled by default,
    # no need to redefine it in your config for now)
    #media-session.enable = true;
  };
#+end_src

***  Users
#+begin_src nix
  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.primary = {
    isNormalUser = true;
    description = "Primary";
    extraGroups = [ "networkmanager" "wheel" "docker" ];
  };
#+end_src

***  Docker
#+begin_src nix
virtualisation.docker.enable = true;
#+end_src
***  Flatpak
#+begin_src nix
services.flatpak.enable = true;
#+end_src
***  Nix Packages
These are *SYSTEM* packages for user specific look at home settings
****  General Dependencies
#+begin_src nix
environment.systemPackages = with pkgs; [
  neovim
  fastfetch
  git
  curl
  wget
  htop
  stow
  fzf
#+end_src
****  Terminal (kitty)
#+begin_src nix
  kitty
#+end_src
****  Hyprland
#+begin_src nix
  hyprpaper
  wofi
  waybar

  waypaper
  brightnessctl
#+end_src
****  Emacs (DOOM)
#+begin_src nix
  # Emacs
  gcc
  gnumake
  ripgrep
  fd
  emacs
  cmake
  libtool
  ispell

  # For emms
  mpv
#+end_src
*****  Bash
#+begin_src nix
  # Shell Check
  shellcheck

  # Formatter
  shfmt
#+end_src
*****  Clojure
#+begin_src nix
# Clojure
clojure

# Script runtime (babashka)
babashka

# Formatter
cljfmt

# Linter
clj-kondo
#+end_src
*****  Go
#+begin_src nix
# Golang
go

# Go modify tags
gomodifytags

# Tests
gotests

# go repl (gore)
gore

# Go language server (gopls)
gopls

# Go debugger
delve
#+end_src
*****  Nix
#+begin_src nix
# Formatter
nixfmt
#+end_src
*****  Org
#+begin_src nix
# For org roam
graphviz
#+end_src
*****  Python
#+begin_src nix
  # Python
  python3

  # LSP (pyright in my case)
  pyright

  # Python Formatter
  black
  # Import management
  python3Packages.pyflakes

  # Python debugger
  python3Packages.debugpy

#+end_src
****  Fonts
#+begin_src nix
nerd-fonts.symbols-only
nerd-fonts.iosevka

# Chinese Font
noto-fonts-cjk-sans
noto-fonts-cjk-serif
#+end_src
****  More Developer Tools
#+begin_src nix
  # Devops
  kubectl
  docker
  terraform
  google-cloud-sdk
#+end_src

****  Flatpak
Why Flatpak? for sandboxing certain apps I wish to have more restrictive permissions
#+begin_src nix
flatpak
#+end_src
****  Misc
#+begin_src nix
];
}
#+end_src
*  Waybar (waybar/ directory)
:PROPERTIES:
:header-args: :tangle ./waybar/config.jsonc
:VISIBILITY: folded
:END:

**  Basic Settings
#+begin_src js
{
    "layer": "top", // Waybar at top layer
    // "position": "bottom", // Waybar position (top|bottom|left|right)
    "height": 30, // Waybar height (to be removed for auto height)
    // "width": 1280, // Waybar width
    "spacing": 4, // Gaps between modules (4px)
    // Choose the order of the modules
    "modules-left": [
        "hyprland/workspaces",
        "hyprland/mode",
        "hyprland/scratchpad",
        "custom/media"
    ],
    "modules-right": [
        "mpd",
        "idle_inhibitor",
        "pulseaudio",
        "network",
        "power-profiles-daemon",
        "cpu",
        "memory",
        "temperature",
        "backlight",
        "keyboard-state",
        "sway/language",
        "battery",
        "battery#bat2",
        "clock",
        "tray",
        "custom/power"
    ],
#+end_src
**  MPD
#+begin_src js
    "mpd": {
        "format": "{stateIcon} {consumeIcon}{randomIcon}{repeatIcon}{singleIcon}{artist} - {album} - {title} ({elapsedTime:%M:%S}/{totalTime:%M:%S}) ⸨{songPosition}|{queueLength}⸩ {volume}% ",
        "format-disconnected": "Disconnected ",
        "format-stopped": "{consumeIcon}{randomIcon}{repeatIcon}{singleIcon}Stopped ",
        "unknown-tag": "N/A",
        "interval": 5,
        "consume-icons": {
            "on": " "
        },
        "random-icons": {
            "off": "<span color=\"#f53c3c\"></span> ",
            "on": " "
        },
        "repeat-icons": {
            "on": " "
        },
        "single-icons": {
            "on": "1 "
        },
        "state-icons": {
            "paused": "",
            "playing": ""
        },
        "tooltip-format": "MPD (connected)",
        "tooltip-format-disconnected": "MPD (disconnected)"
    },
#+end_src
**  Idle_inhibitor
#+begin_src js
    "idle_inhibitor": {
        "format": "{icon}",
        "format-icons": {
            "activated": "",
            "deactivated": ""
        }
    },
#+end_src
**  Tray
#+begin_src js
    "tray": {
        // "icon-size": 21,
        "spacing": 10,
        // "icons": {
        //   "blueman": "bluetooth",
        //   "TelegramDesktop": "$HOME/.local/share/icons/hicolor/16x16/apps/telegram.png"
        // }
    },
#+end_src
**  Clock
#+begin_src js
    "clock": {
        "timezone": "America/Chicago",
        "format": "{:%I:%M %p}",
        "format-alt": "{:%m-%d-%Y}"
    },
#+end_src
**  CPU
#+begin_src js
    "cpu": {
        "format": "{usage}% ",
        "tooltip": false
    },
#+end_src
**  Memory
#+begin_src js
    "memory": {
        "format": "{}% "
    },
#+end_src
**  Temperature
#+begin_src js
    "temperature": {
        // "thermal-zone": 2,
        // "hwmon-path": "/sys/class/hwmon/hwmon2/temp1_input",
        "critical-threshold": 80,
        // "format-critical": "{temperatureC}°C {icon}",
        "format": "{temperatureC}°C {icon}",
        "format-icons": ["", "", ""]
    },
#+end_src
**  Backlight
#+begin_src js
    "backlight": {
        // "device": "acpi_video1",
        "format": "{percent}% {icon}",
        "format-icons": ["", "", "", "", "", "", "", "", ""]
    },
#+end_src
**  Battery
#+begin_src js
    "battery": {
        "states": {
            // "good": 95,
            "warning": 30,
            "critical": 15
        },
        "format": "{capacity}% {icon}",
        "format-full": "{capacity}% {icon}",
        "format-charging": "{capacity}% ",
        "format-plugged": "{capacity}% ",
        "format-alt": "{time} {icon}",
        // "format-good": "", // An empty format will hide the module
        // "format-full": "",
        "format-icons": ["", "", "", "", ""]
    },
    "battery#bat2": {
        "bat": "BAT2"
    },
#+end_src
**  Power Profiles
#+begin_src js
    "power-profiles-daemon": {
      "format": "{icon}",
      "tooltip-format": "Power profile: {profile}\nDriver: {driver}",
      "tooltip": true,
      "format-icons": {
        "default": "Balanced",
        "performance": "Performance",
        "balanced": "Balanced",
        "power-saver": "Power-Saver"
      }
    },
#+end_src
**  Custom Power
#+begin_src js
    "custom/power": {
        "format" : "⏻ ",
		"tooltip": false,
		"menu": "on-click",
		"menu-file": "$HOME/.config/waybar/power_menu.xml", // Menu file in resources folder
		"menu-actions": {
			"shutdown": "shutdown",
			"reboot": "reboot",
			"suspend": "systemctl suspend",
			"hibernate": "systemctl hibernate"
		}
    },
#+end_src
**  Network
#+begin_src js
    "network": {
        // "interface": "wlp2*", // (Optional) To force the use of this interface
        "format-wifi": "{essid} ({signalStrength}%) ",
        "format-ethernet": "{ipaddr}/{cidr} ",
        "tooltip-format": "{ifname} via {gwaddr} ",
        "format-linked": "{ifname} (No IP) ",
        "format-disconnected": "Disconnected ⚠",
        "format-alt": "{ifname}: {ipaddr}/{cidr}"
    },
#+end_src
**  PulseAudio
#+begin_src js
    "pulseaudio": {
        // "scroll-step": 1, // %, can be a float
        "format": "{volume}% {icon} {format_source}",
        "format-bluetooth": "{volume}% {icon} {format_source}",
        "format-bluetooth-muted": " {icon} {format_source}",
        "format-muted": " {format_source}",
        "format-source": "{volume}% ",
        "format-source-muted": "",
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", "", ""]
        },
        "on-click": "pavucontrol"
    },
}
#+end_src
