#+title: Config Files

This is where I keep all of my dotfiles for all of my software

* Table of contents :TOC_4:
- [[#main-software][Main Software]]
- [[#how-to-install][How to install]]

* Main Software
+ Editor: DOOM Emacs
+ Window Manager: Sway
+ Terminal: Foot
+ Status Bar: Waybar
+ Launcher: Wofi
+ GNU/Linux Distro: Nixos



* How to install
The main way I install this is grabbing a graphical installer ISO from [[https://nixos.org/download/][nixos.org]].
After the initial install, I install git and then clone this repository.

Usually into a Workspace directory under a Misc directory. (But location doesn't matter)
#+begin_src bash
git clone https://github.com/Zivision/configs.git ~/Workspace/Misc/configs
#+end_src

After cloning the repository, run *nix develop*
#+begin_src bash
nix develop
#+end_src

after that simply run the following command listed below WARNING: nixbox is the
minimal setup and does NOT have NVIDIA drivers. Look at
PROJECT_ROOT/org/nixos.org for the full in depth configuration.
#+begin_src bash
~/Workspace/Misc/configs/bin/manage-system -ci nixbox
#+end_src

