#+title: Doom Config

*  Doom config setting :TOC_4:
-  [[#init-settings][Init settings]]
  -  [[#input][Input]]
  -  [[#completion][Completion]]
  -  [[#ui][UI]]
  -  [[#editor][Editor]]
  -  [[#emacs][Emacs]]
  -  [[#term][Term]]
  -  [[#checkers][Checkers]]
  -  [[#tools][Tools]]
  -  [[#os][OS]]
  -  [[#lang][Lang]]
  -  [[#email][Email]]
  -  [[#app][App]]
  -  [[#config][Config]]
-  [[#config-settings][Config settings]]
  -  [[#basic-usage][Basic usage]]
    -  [[#basic-variables][Basic variables]]
    -  [[#basic-macros][Basic macros]]
  -  [[#basic-settings][Basic settings]]
    -  [[#fonts][Fonts]]
    -  [[#theme][Theme]]
      -  [[#set-theme][Set Theme]]
    -  [[#line-numbers][Line numbers]]
    -  [[#transparency][Transparency]]
  -  [[#package-settings][Package settings]]
    -  [[#emms][EMMS]]
    -  [[#prism][Prism]]
    -  [[#org][Org]]
      -  [[#org-modern][Org Modern]]
      -  [[#org-appear][Org Appear]]
      -  [[#org-download][Org Download]]
      -  [[#org-toc][Org TOC]]
      -  [[#olivetti][Olivetti]]
      -  [[#misc-org-settings][Misc org settings]]
    -  [[#lispy][Lispy]]
-  [[#packages-settings][Packages settings]]
  -  [[#basic-usage-1][Basic usage]]
  -  [[#external-packages][External Packages]]
    -  [[#org-packages][Org Packages]]
      -  [[#org-modern-1][Org Modern]]
      -  [[#org-appear-1][Org appear]]
      -  [[#org-table-of-contents][Org table of contents]]
      -  [[#org-download-1][Org Download]]
      -  [[#olivetti-1][Olivetti]]
    -  [[#themes-and-style][Themes and Style]]
      -  [[#prism-1][Prism]]
    -  [[#misc-and-fun][Misc and fun]]
      -  [[#fireplace][Fireplace]]
      -  [[#nyan-mode][Nyan Mode]]

*  Init settings
**  Input
#+begin_src emacs-lisp :tangle init.el
(doom! :input
       ;;bidi              ; (tfel ot) thgir etirw uoy gnipleh
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row
#+end_src
**  Completion
#+begin_src emacs-lisp :tangle init.el
       :completion
       ;;company           ; the ultimate code completion backend
       (corfu +orderless)  ; complete with cap(f), cape and a flying feather!
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       vertico           ; the search engine of the future
#+end_src
**  UI
#+begin_src emacs-lisp :tangle init.el
       :ui
       ;;deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       ;;doom-quit         ; DOOM quit-message prompts when you quit Emacs
       ;;(emoji +unicode)  ; 🙂
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;indent-guides     ; highlighted indent columns
       ;;ligatures         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;smooth-scroll     ; So smooth you won't believe it's not butter
       ;;tabs              ; a tab bar for Emacs
       ;;treemacs          ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       (vc-gutter +pretty) ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       ;;zen               ; distraction-free coding or writing
#+end_src
**  Editor
#+begin_src emacs-lisp :tangle init.el
       :editor
       (evil +everywhere) ; come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       ;;(format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       lispy             ; vim for lisp, for people who don't like vim
       ;;multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       (whitespace +guess +trim)  ; a butler for your whitespace
       ;;word-wrap         ; soft wrapping with language-aware indent
#+end_src
**  Emacs
#+begin_src emacs-lisp :tangle init.el
       :emacs
       dired             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       eww               ; the internet is gross
       ibuffer           ; interactive buffer management
       tramp             ; remote files at your arthritic fingertips
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree
#+end_src
**  Term
#+begin_src emacs-lisp :tangle init.el
       :term
       eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm             ; the best terminal emulation in Emacs
#+end_src
**  Checkers
#+begin_src emacs-lisp :tangle init.el
       :checkers
       syntax              ; tasing you for every semicolon you forget
       (spell +flyspell) ; tasing you for misspelling mispelling
       grammar           ; tasing grammar mistake every you make
#+end_src
**  Tools
#+begin_src emacs-lisp :tangle init.el
       :tools
       ;;ansible
       ;;biblio            ; Writes a PhD for you (citation needed)
       ;;collab            ; buffers with friends
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       lookup              ; navigate your code and its documentation
       ;;llm               ; when I said you needed friends, I didn't mean...
       (lsp +eglot)      ; M-x vscode
       magit             ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       ;;pdf               ; pdf enhancements
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       (tree-sitter
        +everywhere)       ; syntax and parsing, sitting in a tree...
       ;;upload            ; map local to remote projects via ssh/ftp
#+end_src
**  OS
#+begin_src emacs-lisp :tangle init.el
       :os
       (:if (featurep :system 'macos) macos)  ; improve compatibility with macOS
       ;;tty               ; improve the terminal Emacs experience
#+end_src
**  Lang
#+begin_src emacs-lisp :tangle init.el
       :lang
       ;;ada               ; In strong typing we (blindly) trust
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       ;;(cc +lsp)         ; C > C++ == 1
       clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fortran           ; in FORTRAN, GOD is REAL (unless declared INTEGER)
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       (go +lsp)         ; the hipster dialect
       ;;(graphql +lsp)    ; Give queries a REST
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       ;;json              ; At least it ain't XML
       ;;janet             ; Fun fact: Janet is me!
       ;;(java +lsp)       ; the poster child for carpal tunnel syndrome
       (javascript
        +lsp)        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       ;;latex             ; writing papers in Emacs has never been so fun
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be
       ;;lua               ; one-based indices? one-based indices
       markdown          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org
        +roam2)               ; organize your plain life in plain text
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;graphviz          ; diagrams for confusing yourself even more
       ;;purescript        ; javascript, but functional
       python            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       ;;rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;(rust +lsp)       ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       sh                ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       ;;web               ; the tubes
       yaml              ; JSON, but readable
       ;;zig               ; C, but simpler
#+end_src
**  Email
#+begin_src emacs-lisp :tangle init.el
       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)
#+end_src
**  App
#+begin_src emacs-lisp :tangle init.el
       :app
       ;;calendar
       (emms +mpv)         ; music player with mpv backend.
       ;;everywhere        ; *leave* Emacs!? You must be joking
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader
#+end_src
**  Config
#+begin_src emacs-lisp :tangle init.el
       :config
       ;;literate
       (default +bindings +smartparens))
#+end_src

*  Config settings
**  Basic usage
***  Basic variables
+ doom-font                :: the primary font to use
+ doom-variable-pitch-font :: a non-monospace font (where applicable)
+ doom-big-font            :: used for big font
+ doom-symbol-font         :: for symbols
+ doom-serif-font          :: serif font

***  Basic macros
+ after!         :: Used for configuring packages doom might override
+ load!          :: Load external .el files
+ use-package!   :: Configure packages
+ after!         :: For running code after a package has loaded
+ add-load-path! :: For adding directories to the load-path.
+ map!           :: Map new keys

**  Basic settings
***  Fonts
#+begin_verse
Will need to download the Iosevka Nerd font for this to work
#+end_verse
#+begin_src emacs-lisp :tangle config.el
(setq doom-font (font-spec :family "Iosevka Nerd Font Mono" :size 20))
(setq doom-serif-font (font-spec :family "DejaVu Serif" :size 20))
#+end_src
***  Theme
****  Set Theme
#+begin_src emacs-lisp :tangle config.el
(setq doom-theme 'doom-gruvbox)
#+end_src
***  Line numbers
#+begin_src emacs-lisp :tangle config.el
(setq display-line-numbers-type `relative)
#+end_src
***  Transparency
#+begin_verse
Change the numerical values to affect the transparency
(0-100 where 100 is opaque)
#+end_verse
#+begin_src emacs-lisp :tangle config.el
(set-frame-parameter (selected-frame) 'alpha '(90 . 90))
(add-to-list 'default-frame-alist '(alpha . (90 . 90)))
#+end_src
**  Package settings
***  EMMS
#+begin_verse
This is the music player I use
#+end_verse
#+begin_src emacs-lisp :tangle config.el
(use-package! emms
  :config
  (setq emms-source-file-default-directory "~/Music/Music")
  (setq emms-player-list '(emms-player-mpv)))
#+END_SRC
***  Prism
#+begin_verse
Colored parenthesis (colored lisp go brrr)
#+end_verse
#+begin_src emacs-lisp :tangle config.el

(use-package! prism
  :init
  (setq prism-desaturations '(10 15 20))
  :hook (((clojure-mode emacs-lisp-mode) . prism-mode)))

#+end_src
***  Org
#+begin_verse
All of my org settings
first my default org directory
#+end_verse
#+begin_src emacs-lisp :tangle config.el
(setq org-directory "~/Documents/org")
(after! org
  (setq org-hide-emphasis-markers t))
#+end_src
****  Org Modern
#+begin_verse
This makes org mode nicer to look at
#+end_verse
#+begin_src emacs-lisp :tangle config.el
;; Org modern settings
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  ;; Basic settings
  (setq org-modern-star '("◉" "○" "✸" "✿" "✤" "✜" "◆" "▶")
        org-modern-table-vertical 1
        org-modern-table-horizontal 0.2
        org-modern-list '((43 . "➤") (45 . "–") (42 . "•"))
        org-modern-block-fringe nil
        org-modern-todo-faces
        '(("TODO" :background "red" :foreground "white")
          ("DONE" :background "green" :foreground "white")
          ("NOTE" :background "blue" :foreground "white")))
  ;; Source code block settings
  (setq org-src-fontify-natively t      ; Syntax highlight in code blocks
        org-src-tab-acts-natively t      ; Tab works normally in code blocks
        org-src-preserve-indentation t))  ; Preserve indentation
#+end_src
****  Org Appear
#+begin_src emacs-lisp :tangle config.el
(use-package! org-appear
  :after org-modern
  :hook (org-mode . org-appear-mode))
#+END_SRC
****  Org Download
#+begin_src emacs-lisp :tangle config.el
(setq-default org-download-image-dir "~/Pictures/Org")
#+end_src
****  Org TOC
#+begin_src emacs-lisp :tangle config.el
(use-package! toc-org
  :hook (org-mode . toc-org-mode))
#+END_SRC
****  Olivetti
#+begin_verse
Used to center org documents
#+end_verse
#+begin_src emacs-lisp :tangle config.el
(use-package! olivetti
  :hook (org-mode . olivetti-mode)
  :config (setq olivetti-body-width 100))
#+end_src
****  Misc org settings
#+begin_src emacs-lisp :tangle config.el
(after! org
  (setq org-babel-python-command "python3") ; Sets python to "python3"
  (setq org-babel-default-header-args:python '((:results . "output")))) ; Sets results to output
#+end_src

***  Lispy
#+begin_src emacs-lisp :tangle config.el
(map! :leader
      :prefix "l"
      "r" #'lispy-raise
      "b" #'lispy-barf
      "s" #'lispy-slurp)
#+end_src
*  Packages settings
**  Basic usage
1. Declare them here in a `package!' statement,
2. Run 'doom sync' in the shell,
3. Restart Emacs.
NOTE: for more info on packages look at the documentation (SPC h d h) or more specifically
C-h f package\!
**  External Packages
***  Org Packages
****  Org Modern
#+begin_src emacs-lisp :tangle packages.el
(package! org-modern)
#+end_src
****  Org appear
#+begin_src emacs-lisp :tangle packages.el
(package! org-appear)
#+END_SRC
****  Org table of contents
#+begin_src emacs-lisp :tangle packages.el
(package! toc-org)
#+END_SRC
****  Org Download
#+begin_src emacs-lisp :tangle packages.el
(package! org-download)
#+end_src
****  Olivetti
#+begin_src emacs-lisp :tangle packages.el
(package! olivetti)
#+end_src
***  Themes and Style
****  Prism
#+begin_src emacs-lisp :tangle packages.el
(package! prism)
#+end_src
***  Misc and fun
****  Fireplace
*Hello World*
#+begin_src emacs-lisp :tangle packages.el
(package! fireplace)
#+end_src
****  Nyan Mode
#+begin_src emacs-lisp :tangle packages.el
(package! nyan-mode)
#+end_src
