#+title: GNU Guix setup
This is a basic setup for GNU Guix.

*  GNU Guix Table of Contents :TOC_4:
-  [[#how-to-install][How to Install]]
-  [[#guix-config][Guix Config]]
  -  [[#basic-settings][Basic Settings]]
  -  [[#packages][Packages]]
    -  [[#emacs][Emacs]]
  -  [[#services][Services]]
-  [[#bashrc-config][Bashrc Config]]
  -  [[#basic-settings-1][Basic Settings]]
  -  [[#history-configuration][History Configuration]]
  -  [[#shell-options][Shell Options]]
  -  [[#prompt][Prompt]]
  -  [[#aliases][Aliases]]
  -  [[#environment-variables][Environment Variables]]
  -  [[#guix-profile][Guix profile]]

*  How to Install
:PROPERTIES:
:VISIBILITY: folded
:END:
To install grab the dependancies first (for mint/ubuntu):
#+begin_src bash
sudo apt update
sudo apt install wget gpg xz-utils
#+end_src
This is optional however, it gets better preformance:
#+begin_src bash
sudo apt install nscd
sudo systemctl enable nscd
sudo systemctl start nscd
#+end_src

After the essentials, install the script form the [[https://guix.gnu.org/manual/en/html_node/Binary-Installation.html][Guix Documentation Page]]:
#+begin_src bash
cd /tmp
wget -O guix-install.sh https://guix.gnu.org/install.sh
chmod +x guix-install.sh
sudo ./guix-install.sh
#+end_src

Use these command and *NOT* the apt package! Follow the directions and in the next step.

Update everything by running guix pull
*WARNING* this will take a while!
#+begin_src bash
guix pull
#+end_src

And update .bashrc (.bash_profile) with these commands:
#+begin_src bash
GUIX_PROFILE="$HOME/.config/guix/current"
. "$GUIX_PROFILE/etc/profile"
#+end_src

*  Guix Config
:PROPERTIES:
:VISIBILITY: folded
:END:
This is where the main Guix scheme files lives
**  Basic Settings
#+begin_src scheme :tangle home-configuration.scm
(use-modules (gnu home)
             (gnu packages)
             (gnu packages emacs)
             (gnu services)
             (guix gexp)
             (gnu home services shells))
#+end_src
**  Packages
***  Emacs
#+begin_src scheme :tangle home-configuration.scm
(home-environment
  ;; Packages to install
  (packages (specifications->packages
             '("emacs"
               "git"
               "ripgrep"
               "fd"
               "shellcheck")))
#+end_src

**  Services
#+begin_src scheme :tangle home-configuration.scm
(services
 (list
  ;; Manage your bash config
  (service home-bash-service-type
           (home-bash-configuration
            (aliases '(("ll" . "ls -l")
                       ("doom" . "~/.config/emacs/bin/doom")))
            (bashrc (list (local-file "bashrc.sh"))))))))
#+end_src

*  Bashrc Config
:PROPERTIES:
:VISIBILITY: folded
:END:

This is the bashrc I use with guix. Just makes thing easier to place it here.
**  Basic Settings
#+begin_src bash :tangle bashrc.sh
#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
#+end_src
**  History Configuration
#+begin_src bash :tangle bashrc.sh
HISTSIZE=10000                # Commands to keep in memory
HISTFILESIZE=20000            # Commands to keep in history file
HISTCONTROL=ignoreboth        # Ignore duplicates and commands starting with space
shopt -s histappend           # Append to history file, don't overwrite
#+end_src
**  Shell Options
#+begin_src bash :tangle bashrc.sh
shopt -s checkwinsize         # Update LINES and COLUMNS after each command
shopt -s globstar 2>/dev/null # Enable ** for recursive glob matching
shopt -s cdspell              # Autocorrect minor spelling errors in cd
#+end_src
**  Prompt
#+begin_src bash :tangle bashrc.sh
# Function to get current git branch
git_branch() {
    local branch=$(git branch 2>/dev/null | grep '^*' | colrm 1 2)
    if [ -n "$branch" ]; then
        echo "($branch) "
    fi
}

# Prompt
PS1='\[\033[01;32m\][\u@\h]\[\033[00m\] >>> \[\033[01;34m\]\w\[\033[00m\] \[\033[01;33m\]$(git_branch)\[\033[00m\]\n\[\033[01;90m\]\A\[\033[00m\] λ '
#+end_src
**  Aliases
#+begin_src bash :tangle bashrc.sh
# Listing
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ls -lAh'
alias l='ls -CF'

# Safety nets
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Shortcuts
alias grep='grep --color=auto'
alias df='df -h'
alias du='du -h'
alias free='free -h'

# Git shortcuts (if you use git)
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'
#+end_src
**  Environment Variables
#+begin_src bash :tangle bashrc.sh
export EDITOR=emacs
export VISUAL=emacs

# Add your custom PATH modifications below:
export PATH="$HOME/.local/bin:$PATH"

# ASDF
export ASDF_DATA_DIR="/your/custom/data/dir"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
. <(asdf completion bash)
#+end_src
**  Guix profile
#+begin_src bash :tangle bashrc.sh
if [ -f "$HOME/.guix-profile/etc/profile" ]; then
    . "$HOME/.guix-profile/etc/profile"
fi
#+end_src
