#!/usr/bin/env sh
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
PROJECT_DIR=$(dirname "$SCRIPT_DIR")

# Update repositories
echo "Updating Repositories"
sudo apt update

echo "Installing general packages"
sudo apt install emacs stow ripgrep fd-find -y

echo "Installing DOOM Emacs dependencies."
sudo apt install libjansson4 libjansson-dev cmake libtool-bin

rm ~/.bashrc

# Stow packages
(cd "$PROJECT_DIR" && stow doom -t ~/.config/doom)
(cd "$PROJECT_DIR" && stow home -t ~)
(cd "$PROJECT_DIR" && stow scripts -t ~/.local/bin)

git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs

# Install doom emacs
~/.config/emacs/bin/doom install

echo "Install finished"
