#+title: Nixos Configuration

* Table of Contents :TOC_4:noexport:
- [[#flake-setttings][Flake Setttings]]
  - [[#description][Description]]
  - [[#inputs][Inputs]]
  - [[#outputs][Outputs]]
    - [[#nixos-configurations][Nixos Configurations]]
      - [[#swiftx][Swiftx]]
      - [[#nixbox][NixBox]]
    - [[#dev-shell][Dev shell]]
      - [[#default][Default]]
      - [[#install][Install]]
  - [[#end-of-flake][End of flake]]
- [[#home-settings][Home Settings]]
  - [[#imports][Imports]]
  - [[#basic-settings][Basic Settings]]
  - [[#direnv][Direnv]]
  - [[#config-file-linking][Config File linking]]
    - [[#home-file][Home File]]
    - [[#kitty][Kitty]]
    - [[#waybar][Waybar]]
    - [[#wofi][Wofi]]
    - [[#sway][Sway]]
    - [[#swaylock][Swaylock]]
    - [[#mako][Mako]]
    - [[#foot][Foot]]
    - [[#kde-wallet][KDE Wallet]]
    - [[#end-of-list][End of list]]
  - [[#thunderbird-email][Thunderbird (email)]]
  - [[#bash-management][Bash management]]
  - [[#packages][Packages]]
    - [[#start-of-list][Start of List]]
    - [[#office-tools][Office Tools]]
    - [[#games][Games]]
    - [[#sway-pkgs][Sway (PKGS)]]
    - [[#browser][Browser]]
    - [[#video-editing][Video Editing]]
    - [[#audio-editing][Audio Editing]]
    - [[#text-editors][Text editors]]
    - [[#emacs][Emacs]]
    - [[#other-packages][Other Packages]]
    - [[#fonts][Fonts]]
    - [[#terminal][Terminal]]
    - [[#end-of-list-1][End of list]]
- [[#systems][Systems]]
  - [[#swiftx-1][SwiftX]]
  - [[#nixbox-1][NixBox]]
- [[#configuration-settings][Configuration Settings]]
  - [[#nvidia][Nvidia]]
    - [[#lts-kernel][LTS Kernel]]
    - [[#open-gl][Open GL]]
    - [[#drivers-and-hardware-settings][Drivers and Hardware Settings]]
  - [[#configuration][Configuration]]
    - [[#imports-1][Imports]]
    - [[#bootloader][Bootloader]]
    - [[#app-armor][App armor]]
    - [[#nix-packages-manager][Nix (Packages manager)]]
    - [[#steam][Steam]]
    - [[#system][System]]
    - [[#syncthing][Syncthing]]
    - [[#gnupg][Gnupg]]
    - [[#wayland][Wayland]]
    - [[#sway-1][Sway]]
    - [[#polkit][Polkit]]
    - [[#flakes][Flakes]]
    - [[#desktop][Desktop]]
    - [[#audio][Audio]]
    - [[#users][Users]]
    - [[#docker][Docker]]
    - [[#virt-manager][Virt Manager]]
    - [[#flatpak][Flatpak]]
    - [[#nix-packages][Nix Packages]]
      - [[#start-of-list-1][Start of List]]
      - [[#sway-lock-lock-screen][Sway Lock (Lock Screen)]]
      - [[#more-developer-tools][More Developer Tools]]
      - [[#flatpak-1][Flatpak]]
      - [[#end-of-list-2][End of List]]

* Flake Setttings
:PROPERTIES:
:header-args: :tangle ../flake.nix
:VISIBILITY: folded
:END:
** Description
#+begin_src nix
{
  description = "My system flake";
#+end_src

** Inputs
#+begin_src nix
inputs = {
  # NixOS official package source, using the nixos-26.05 branch here
  nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
  # Home manager
  home-manager = {
    url = "github:nix-community/home-manager/release-26.05";
    inputs.nixpkgs.follows = "nixpkgs";
  };
};
#+end_src

** Outputs
#+begin_src nix
outputs = { self, nixpkgs, home-manager, ... }@inputs:
let
  system = "x86_64-linux";
  legacyPkgs = nixpkgs.legacyPackages.${system};
in
{
#+end_src
*** Nixos Configurations
#+begin_src nix
  nixosConfigurations = {
#+end_src
**** Swiftx
#+begin_src nix
    swiftx = nixpkgs.lib.nixosSystem {
      modules = [
        # Import the previous configuration.nix we used,
        # so the old configuration file still takes effect
        ./build/nixos/configuration.nix
        ./build/nixos/nvidia.nix
        ./build/nixos/swiftx.nix

        # Import home manager
        home-manager.nixosModules.home-manager
        {
          home-manager.useGlobalPkgs = true;
          home-manager.useUserPackages = true;
          home-manager.users.primary = import ./build/nixos/home.nix;
        }
      ];
    };
#+end_src
**** NixBox
#+begin_src nix
    nixbox = nixpkgs.lib.nixosSystem {
      modules = [
        # Import the previous configuration.nix we used,
        # so the old configuration file still takes effect
        ./build/nixos/configuration.nix
        ./build/nixos/nixbox.nix

        # Import home manager
        home-manager.nixosModules.home-manager
        {
          home-manager.useGlobalPkgs = true;
          home-manager.useUserPackages = true;
          home-manager.users.primary = import ./build/nixos/home.nix;
        }
      ];
    };
  };
#+end_src
*** Dev shell
#+begin_src nix
devShells.${system}= {
#+end_src
**** Default
#+begin_src nix
default = legacyPkgs.mkShell {
  packages = with legacyPkgs; [
    pyright
    black
    python313Packages.pyflakes
    python313Packages.isort
  ];
  shellHook = ''
    echo "Dev Envrionment Ready!"
  '';
};


#+end_src
**** Install
#+begin_src nix
install = legacyPkgs.mkShell {
  packages = with legacyPkgs; [
    git
    emacs
    python3
  ];
  shellHook = ''
    echo "Ready to build new nix machine!"
  '';
};

#+end_src
** End of flake
#+begin_src nix
};
};
}

#+end_src

* Home Settings
:PROPERTIES:
:header-args: :tangle ../build/nixos/home.nix
:VISIBILITY: folded
:END:

** Imports
#+begin_src nix
{ config, lib, pkgs, ... }:
#+end_src
** Basic Settings
#+begin_src nix
{
  home.username = "primary";
  home.homeDirectory = "/home/primary";
  home.stateVersion = "26.05";
#+end_src
** Direnv
#+begin_src nix
programs.direnv = {
  enable = true;
  nix-direnv.enable = true;
};
#+end_src
** Config File linking
*** Home File
#+begin_src nix
home.file = {
#+end_src
*** Kitty
#+begin_src nix
".config/kitty" = {
  source = ../kitty;
  recursive = true;
};
#+end_src
*** Waybar
#+begin_src nix
".config/waybar" = {
  source = ../waybar;
  recursive = true;

};
#+end_src
*** Wofi
#+begin_src nix
".config/wofi" = {
  source = ../wofi;
  recursive = true;
};
#+end_src
*** Sway
#+begin_src nix
".config/sway" = {
  source = ../sway;
  recursive = true;
};
#+end_src
*** Swaylock
#+begin_src nix
".config/swaylock" = {
  source = ../swaylock;
  recursive = true;
};
#+end_src
*** Mako
#+begin_src nix
".config/mako" = {
  source = ../mako;
  recursive = true;
};
#+end_src
*** Foot
#+begin_src nix
".config/foot" = {
  source = ../foot;
  recursive = true;
};
#+end_src
*** KDE Wallet
#+begin_src nix
".config/kwalletrc".text = ''
  [Wallet]
  Enabled=false
'';
#+end_src
*** End of list
#+begin_src nix
};
#+end_src
** Thunderbird (email)
#+begin_src nix
programs.thunderbird.enable = true;
#+end_src

** Bash management
#+begin_src nix
programs.bash = {
    enable = true;
    initExtra = builtins.readFile ../home/.bashrc;

    sessionVariables = {
      EDITOR = "nvim";
    };
  };

#+end_src

** Packages
*** Start of List
#+begin_src nix
home.packages = with pkgs; [
#+end_src
*** Office Tools
#+begin_src nix
  libreoffice-qt6-fresh
  hunspell
  hunspellDicts.uk_UA
  hunspellDicts.th_TH
#+end_src
*** Games
#+begin_src nix
(prismlauncher.override {
  jdks = [

    zulu25
    zulu8
  ];
})
#+end_src
*** Sway (PKGS)
#+begin_src nix
   wl-clipboard
   mako
   swaybg
   wofi
   waybar
   waypaper
#+end_src
*** Browser
#+begin_src nix
# Start of the home packages array
brave
firefox
#+end_src
*** Video Editing
#+begin_src nix
kdePackages.kdenlive
#+end_src
*** Audio Editing
#+begin_src nix
audacity
#+end_src
*** Text editors
#+begin_src nix
# For Emacs
  python3
  gcc
  gnumake
  ripgrep
  fd
  cmake
  libtool
  ispell
  # Org mode
  graphviz

  # MPV for emms
  mpv
  # Neovim for quick edits
  neovim

  # Nix format
  nixfmt

  # Shell stuff
  shellcheck
  shfmt
#+end_src

*** Emacs
#+begin_src nix
# emacs itself
((emacsPackagesFor emacs-pgtk).emacsWithPackages (epkgs: with epkgs; [
  mu4e
  evil
  evil-collection
  general
  which-key
  doom-modeline
  vertico
  consult
  orderless
  magit
  emms
  nerd-icons-dired
  nerd-icons-completion
  golden-ratio
  vterm
  corfu
  cape
  apheleia
  beacon
  yasnippet
  vertico-posframe
  marginalia
  embark
  embark-consult
  undo-fu
  dashboard
  envrc
  
  # Elfeed
  elfeed
  elfeed-org
  elfeed-tube
  elfeed-tube-mpv
  
  # Themes
  doom-themes
  jazz-theme
  badwolf-theme
  
  # Eshell
  eshell-syntax-highlighting
  eshell-prompt-extras

  # Org mode
  olivetti
  org-modern
  org-appear
  toc-org
  org-roam

  ## Languages
  # Python
  lsp-pyright
  pet
  pyvenv

  # Nix
  nix-mode
]))
#+end_src
*** Other Packages
#+begin_src nix
fastfetch
  git
  curl
  wget
  htop
  fzf
  findutils.locate
  yt-dlp
  vips
  ffmpegthumbnailer
  mediainfo
  jq
#+end_src
*** Fonts
#+begin_src nix
# Fonts for emacs
nerd-fonts.symbols-only
nerd-fonts.iosevka

# Chinese Font
noto-fonts-cjk-sans
noto-fonts-cjk-serif

#+end_src
*** Terminal
#+begin_src nix
  kitty
#+end_src
*** End of list
#+begin_src nix
];
 }
#+end_src
* Systems
:PROPERTIES:
:VISIBILITY: folded
:END:
** SwiftX
:PROPERTIES:
:header-args: :tangle ../build/nixos/swiftx.nix
:VISIBILITY: folded
:END:
One of my laptops
#+begin_src nix
{
  config,
  lib,
  pkgs,
  ...
}:
# This is for the swift x
{
  # Enable Prime
  hardware.nvidia.prime = {
    sync.enable = true;

    # Make sure to use the correct Bus ID values for your system!
    #intelBusId = "PCI:0:2:0";
    nvidiaBusId = "PCI:04:0:0";
    amdgpuBusId = "PCI:01:0:0";
  };
  hardware.enableAllFirmware = true;
  hardware.enableRedistributableFirmware = true;

  environment.variables = {
  LIBVA_DRIVER_NAME = "nvidia";
  GBM_BACKEND = "nvidia-drm";
  __GLX_VENDOR_LIBRARY_NAME = "nvidia";
  NVD_BACKEND = "direct";
  # For Wayland
  EGL_PLATFORM = "wayland";
  NIXOS_OZONE_WL = "1";
};

}

#+end_src
** NixBox
:PROPERTIES:
:header-args: :tangle ../build/nixos/nixbox.nix
:VISIBILITY: folded
:END:
Main Desktop
#+begin_src nix
{
  config,
  lib,
  pkgs,
  ...
}:
{

  # Use Latest Kernel
  boot.kernelPackages = pkgs.linuxPackages_latest;
}
#+end_src
* Configuration Settings
:PROPERTIES:
:VISIBILITY: folded
:END:
** Nvidia
:PROPERTIES:
:header-args: :tangle ../build/nixos/nvidia.nix
:VISIBILITY: folded
:END:
This is for machines that require nvidia drivers.
This will work on all my machines, but it won't work on all nvidia cards.
Mainly legacy, RTX 20+ should work fine.

WARNING! Set LTS kernel
I set this because running the latest kernel with nvidia ran into issues.
*** LTS Kernel
#+begin_src nix
# Import basic dependancies
{
  config,
  lib,
  pkgs,
  ...
}:
{

  # Set Kernel to lts
  boot.kernelPackages = pkgs.linuxPackages;
#+end_src

*** Open GL
#+begin_src nix
  hardware.graphics = {
    enable = true;
  };
#+end_src
*** Drivers and Hardware Settings
#+begin_src nix
  # Load nvidia driver for Xorg and Wayland
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {

    # Modesetting is required.
    modesetting.enable = true;

    # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
    # Enable this if you have graphical corruption issues or application crashes after waking
    # up from sleep. This fixes it by saving the entire VRAM memory to /tmp/ instead
    # of just the bare essentials.
    powerManagement.enable = false;

    # Fine-grained power management. Turns off GPU when not in use.
    # Experimental and only works on modern Nvidia GPUs (Turing or newer).
    powerManagement.finegrained = false;

    # Use the NVidia open source kernel module (not to be confused with the
    # independent third-party "nouveau" open source driver).
    # Support is limited to the Turing and later architectures. Full list of
    # supported GPUs is at:
    # https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus
    # Only available from driver 515.43.04+
    open = true;

    # Enable the Nvidia settings menu,
    # accessible via `nvidia-settings`.
    nvidiaSettings = true;

    # Optionally, you may need to select the appropriate driver version for your specific GPU.
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };
}
#+end_src

** Configuration
:PROPERTIES:
:header-args: :tangle ../build/nixos/configuration.nix
:VISIBILITY: folded
:END:

This is for global packages and settings I want on all my machines.
*** Imports
#+begin_src nix
{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

#+end_src

*** Bootloader
#+begin_src nix
  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
#+end_src

*** App armor
#+begin_src nix
  # App armor
  security.apparmor.enable = true;
#+end_src
*** Nix (Packages manager)
#+begin_src nix
nix.package = pkgs.nixVersions.latest;
#+end_src
*** Steam
#+begin_src nix
  # Steam
  programs.steam.enable = true;
#+end_src

*** System
#+begin_src nix

networking.hostName = "nixos"; # Define your hostname.
# networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

# Configure network proxy if necessary
# networking.proxy.default = "http://user:password@proxy:port/";
# networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

# Enable networking
networking.networkmanager.enable = true;

# Set your time zone.
time.timeZone = "America/Chicago";

# Select internationalisation properties.

i18n = {
  defaultLocale = "en_US.UTF-8";

  extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  supportedLocales = [
    "en_US.UTF-8/UTF-8"
    "zh_CN.UTF-8/UTF-8"
  ];

  inputMethod = {
    # Available since NixOS 24.11
    enable = true;
    type = "fcitx5";
    fcitx5 = {
      waylandFrontend = true;
      ignoreUserConfig = true;    # Use settings below, ignore user config
      addons = with pkgs; [
        fcitx5-chewing    # Chewing (Traditional Chinese)
        qt6Packages.fcitx5-chinese-addons
        fcitx5-mozc       # Japanese input method
      ];
      settings = {
        inputMethod = {
          "Groups/0" = {
            Name = "Default";
            "Default Layout" = "us";
            DefaultIM = "keyboard-us";
          };
          "Groups/0/Items/0".Name = "keyboard-us";
          "Groups/0/Items/1".Name = "chewing";
          "Groups/0/Items/2".Name = "mozc";
        };
      };
    };
  };
};


nixpkgs.config.allowUnfree = true;

# Firewall
networking.firewall = {
  enable = true;
  allowedTCPPorts = [ 5000 25565 ];
  allowedUDPPorts = [ 5000 25565 ];
};

# This value determines the NixOS release from which the default
# settings for stateful data, like file locations and database versions
# on your system were taken. It‘s perfectly fine and recommended to leave
# this value at the release version of the first install of this system.
# Before changing this value read the documentation for this option
# (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
system.stateVersion = "25.05"; # Did you read the comment?
#+end_src
*** Syncthing
#+begin_src nix
# Example for /etc/nixos/configuration.nix
services.syncthing = {
  enable = true;
  openDefaultPorts = true; # Open ports in the firewall for Syncthing. (NOTE: this will not open syncthing gui port)
  user = "primary";
  dataDir = "/home/primary";
};
#+end_src
*** Gnupg

#+begin_src nix
programs.gnupg.agent = {
  enable = true;
  pinentryPackage = pkgs.pinentry-qt;
};
#+end_src
*** Wayland
#+begin_src nix
environment.sessionVariables.NIXOS_OZONE_WL = "1";
#+end_src
*** Sway
#+begin_src nix
programs.sway = {
  enable = true;
  wrapperFeatures.gtk = true;
};

#+end_src
*** Polkit
#+begin_src nix
security.polkit.enable = true;
#+end_src
*** Flakes
#+begin_src nix
  # Enable flakes
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
#+end_src

*** Desktop
#+begin_src nix
  # Enable the X11 windowing system.
  # You can disable this if you're only using the Wayland session.
  services.xserver.enable = true;

  # Enable the KDE Plasma Desktop Environment.
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true;

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Set editor to neovim for quick edits
  environment.variables.EDITOR = "nvim";
#+end_src

*** Audio
#+begin_src nix
  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    # If you want to use JACK applications, uncomment this
    #jack.enable = true;

    # use the example session manager (no others are packaged yet so this is enabled by default,
    # no need to redefine it in your config for now)
    #media-session.enable = true;
  };
#+end_src

*** Users
#+begin_src nix
  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.primary = {
    isNormalUser = true;
    description = "Primary";
    extraGroups = [ "networkmanager" "wheel" "docker" ];
  };
#+end_src

*** Docker
#+begin_src nix
virtualisation.docker.enable = true;
#+end_src
*** Virt Manager
#+begin_src nix
programs.virt-manager.enable = true;

users.groups.libvirtd.members = ["primary"];

virtualisation.libvirtd.enable = true;

virtualisation.spiceUSBRedirection.enable = true;
#+end_src
*** Flatpak
#+begin_src nix
services.flatpak.enable = true;
#+end_src
*** Nix Packages
These are *SYSTEM* packages for user specific look at home settings
**** Start of List
#+begin_src nix
environment.systemPackages = with pkgs; [
#+end_src
**** Sway Lock (Lock Screen)
#+begin_src nix
swaylock
#+end_src
**** More Developer Tools
#+begin_src nix
  docker
#+end_src

**** Flatpak
Why Flatpak? for sandboxing certain apps I wish to have more restrictive permissions
#+begin_src nix
flatpak
#+end_src
**** End of List
#+begin_src nix
];
}
#+end_src
